mozilla/telemetry-batch-view

README.md, src/main/scala/BatchDerivedStream.scala, src/main/scala/Partitioning.scala, src/main/scala/parquet/ParquetFile.scala
- Add partitioning support
- Increased parallelism level
- Don't recompute dates that already have been processed by an earlier job
=> Various improvements

src/main/scala/streams/Churn.scala
Save the computation for records where we won't need it.
I'm not totally sure what the performance tradeoffs are for the `lazy` keyword, but this seems like a simple optimization for skipping computation on records without clientids.
=> Lazy-init the expensive payload transforms

src/main/scala/DerivedStream.scala
=> Default to processing 'yesterday'

src/main/scala/DerivedStream.scala
Testing doesn't work without AWS credentials, since `DerivedStream` requires them in the initializer.
Making them lazy fixes this.
=> Fix testing

src/main/scala/DerivedStream.scala, src/main/scala/avro/JSON2Avro.scala, src/main/scala/histograms/Histogram.scala, src/main/scala/parquet/ParquetFile.scala, src/main/scala/streams/Longitudinal.scala, src/test/scala/Longitudinal.scala
This patch adds a longitudinal view for release Telemetry data. See
https://bugzilla.mozilla.org/show_bug.cgi?id=1242039.
=> Add longitudinal view.

build.sbt
See bug 1246420 for more details.
=> Increment version for partition naming change.

src/main/scala/streams/Churn.scala
We need 'distributionId' to identify funnelcake builds, and we
add subsessionStartDate to support computing churn based on event
time instead of server timestamp.  Also add subsessionLength for
future work looking at amount of activity over time.
=> Add a few more fields to the Churn dataset

src/main/scala/streams/Longitudinal.scala, src/test/scala/Longitudinal.scala
Ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1247668
All the other fields mentioned in the bug are already present.
=> Add geoCountry and geoCity fields

src/main/scala/DerivedStream.scala, src/main/scala/Partitioning.scala, src/main/scala/SimpleDerivedStream.scala, src/main/scala/streams/ExecutiveStream.scala
We don't currently have a homogeneous versioning convention which is
needed by parquet2hive.
=> Add versioning scheme to datasets.

build.sbt, src/main/scala/streams/Longitudinal.scala, src/test/scala/Longitudinal.scala
Joda-time seems to have very standards-compliant parsing and output.
Ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1250894, #31 .
=> Fix dates with weird time zones.

build.sbt, src/main/scala/streams/Longitudinal.scala, src/test/scala/Longitudinal.scala
Changes from last PR:
* Rebased off master.
* Fixed errors caused by merge and the rebase.
* Profile creation time is actually days since epoch rather than a unix timestamp.
* Change tests to match.
=> Fix date parsing

src/main/scala/streams/Churn.scala
See [Bug 1251259](https://bugzilla.mozilla.org/show_bug.cgi?id=1251259)
=> Add e10sEnabled and e10sCohort to churn dataset.

src/main/scala/DerivedStream.scala
e10sCohort is part of Beta now, so the experiment should basically start as soon as it's released. Today's merge day!
=> Update e10s experiment for beta47

docs/CrashAggregateView.md, src/main/scala/views/CrashAggregateView.scala, src/test/scala/CrashAggregateViewTest.scala
This is the scala port of https://github.com/mozilla/moz-crash-rate-aggregates/pull/11
=> Bug 1270547 - Add content_shutdown_crashes to CrashAggregateView

src/main/scala/views/CrashAggregateView.scala
Ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1275025
=> Use the Telemetry lib instead of getRecords()

src/main/scala/utils/Utils.scala
=> Fix the temporaryFile method to work with Windows-style paths. 

src/main/scala/heka/HekaFrame.scala
This patch adds logging support for errors that occur during the parsing
of Heka files. Note that logs are shown in the Spark UI, see also
https://spark.apache.org/docs/latest/running-on-yarn.html#debugging-your-application.
=> Add logging support for Heka parsing errors.

src/main/scala/com/mozilla/telemetry/DerivedStream.scala, src/main/scala/com/mozilla/telemetry/SimpleDerivedStream.scala, src/main/scala/com/mozilla/telemetry/avro/JSON2Avro.scala, src/main/scala/com/mozilla/telemetry/heka/Dataset.scala, src/main/scala/com/mozilla/telemetry/histograms/Histogram.scala, src/main/scala/com/mozilla/telemetry/parquet/ParquetFile.scala, src/main/scala/com/mozilla/telemetry/streams/Churn.scala, src/main/scala/com/mozilla/telemetry/streams/Longitudinal.scala, src/main/scala/com/mozilla/telemetry/utils/S3.scala, src/main/scala/com/mozilla/telemetry/utils/package.scala, src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala, src/main/scala/com/mozilla/telemetry/views/E10sExperiment.scala, src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala, src/test/scala/com/mozilla/telemetry/ClientCountViewTest.scala, src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala, src/test/scala/com/mozilla/telemetry/LongitudinalTest.scala, src/test/scala/com/mozilla/telemetry/ParquetFile.scala
Once-over through all the scala code to clean up style and formatting.
=> Code cleanup

src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/89)
=> Ignore pings with missing profileSubsessionCounter in longitudinal job.

src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/93)
=> The longitudinal view should go back 6 months by default.

src/main/scala/com/mozilla/telemetry/views/ClientCountView.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/94)
=> The client count view should go back 6 months by default.

src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala, src/test/scala/com/mozilla/telemetry/LongitudinalTest.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/99)
=> Bug 1291369 - Add is_system flag to longitudinal.active_addons

src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala
Helpful for experiment-based and release-based studies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/100)
=> Add environment.settings.e10sCohort to Longitudinal

src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala
This also fixes the breakage due to the introduction
of the is_system property for the active_addons.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/101)
=> Store the AddonRecommender model to S3

src/main/scala/com/mozilla/telemetry/avro/JSON2Avro.scala, src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala
See https://bugzilla.mozilla.org/show_bug.cgi?id=1296242.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/102)
=> Cardinalities of arrays should match.

src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala
r? @vitillo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/103)
=> Train the AddonRecommender only with Firefox data

src/main/scala/com/mozilla/telemetry/views/ClientCountView.scala, src/test/scala/com/mozilla/telemetry/ClientCountViewTest.scala
MainSummaryView v3 uses a nested structure for one of the fields
used by the ClientCountView. Update the code and test case
accordingly.
Downstream consumers of ClientCountView should see no change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/110)
=> Bug 1283471 - Update ClientCountView to use v3

src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, src/test/scala/com/mozilla/telemetry/CrossSectionalViewTest.scala
active_hours by day, geo country mode and number of configs,
architecture and locale mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/113)
=> Add new cross sectional metrics

src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, src/test/scala/com/mozilla/telemetry/CrossSectionalViewTest.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/116)
=> Remove case class hack from xsec view

src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala, src/test/scala/com/mozilla/telemetry/LongitudinalTest.scala
See https://bugzilla.mozilla.org/show_bug.cgi?id=1305043.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/118)
=> Fix ClientIterator trimming bug

.travis.yml, docs/CrashAggregateView.md, src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala, src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/123)
=> Bug 1305742 - Add gfx_compositor to CrashAggregatesView dimensions

src/main/scala/com/mozilla/telemetry/utils/Aggregation.scala, src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, src/test/scala/com/mozilla/telemetry/AggregationTest.scala, src/test/scala/com/mozilla/telemetry/CrossSectionalViewTest.scala
Changed column names from _mon => 0_mon, removed capitalization from agg
type (e.g. geo_Mode -> geo_mode)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/122)
=> Add addon based fields, fix column formatting

docs/CrashAggregateView.md, docs/E10SExperiment.md, docs/available_datasets.md, docs/longitudinal_examples.md
r? @harterrt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/129)
=> Fix up a few links in the docs

README.md
As mentioned by @maurodoglio in IRC
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/131)
=> Document recommended java opts for running tests

src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala, src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/130)
=> Bug 1310673 - Filter out content crash pings from crash aggregates

src/main/scala/com/mozilla/telemetry/utils/Aggregation.scala, src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, src/test/scala/com/mozilla/telemetry/AggregationTest.scala, src/test/scala/com/mozilla/telemetry/CrossSectionalViewTest.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/135)
=> Filter bad subsession lengths

src/main/scala/com/mozilla/telemetry/utils/S3.scala
I didn't see an easy way of adding tests for this since the abstraction used to mock S3 is at the store level for the current tests.
Unfortunately this is a little more difficult to do in the Python Dataset API but I should have a PR for that tomorrow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/126)
=> Bug 1302264 - Support gzip-encoded s3 objects

src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, src/test/scala/com/mozilla/telemetry/CrossSectionalViewTest.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/138)
=> Make cross_sectional handle dates more robustly

src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala
@vitillo, let me know if you'd like to review these commits in separate PRs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/144)
=> Cross Sectional style cleanup

docs/MainSummary.md, src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala, src/test/scala/com/mozilla/telemetry/MainSummaryViewTest.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/147)
=> Bug 1315663 - Add engagement scalars

src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala
Adds a placeholder file to the prefix directory before doing the heavy lifting for longitudinal so that any parallel jobs will trigger the require statement checking for an empty prefix. This is the first quick fix for Bug 1321424 before we work on longer-term fixes for the zombie jobs issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/152)
=> Bug 1321424 - 'lock' output directory to prevent duplicate runs

src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala, src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala
This is to fix the change introduced in https://github.com/mozilla/telemetry-batch-view/pull/130
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/156)
=> Bug 1325974 - retrieve processType from the right field

docs/CrashAggregateView.md, src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala, src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/163)
=> Bug 1314173 - Add gpu crashes to crash aggregate stats

src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, src/test/scala/com/mozilla/telemetry/CrossSectionalViewTest.scala
https://bugzilla.mozilla.org/show_bug.cgi?id=1331630
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/164)
=> Add application_name_mode to xsec dataset

src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
See https://bugzilla.mozilla.org/show_bug.cgi?id=1339421.
=> Make MainSummaryView resilient to invalid JSON.

docs/MainSummary.md, src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala, src/test/scala/com/mozilla/telemetry/MainSummaryViewTest.scala
See Bug  1344274  ( https://bugzilla.mozilla.org/show_bug.cgi?id=1344274 )
=> Added support for computing shutdown_kills.

src/main/scala/com/mozilla/telemetry/utils/MainPing.scala, src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala, src/test/scala/com/mozilla/telemetry/MainSummaryViewTest.scala
[Bug 1339655](https://bugzilla.mozilla.org/show_bug.cgi?id=1339655)
This adds `ssl_handshake_result` to the `main_summary` table. This [validation report](https://gist.github.com/acmiyaguchi/b7deaad26bac276a9fb7d3257d9c6151) shows that it contains valid values.
=> Bug 1339655 - Add SSL_HANDSHAKE_RESULT to main_summary

docs/Addons.md, src/main/scala/com/mozilla/telemetry/views/AddonsView.scala, src/test/scala/com/mozilla/telemetry/AddonsViewTest.scala
=> Bug 1343966 - Add normalized_channel to Addons view

src/main/scala/com/mozilla/telemetry/views/CrashSummaryView.scala, src/test/resources/crash_ping_indented.json, src/test/scala/com/mozilla/telemetry/CrashSummaryViewTest.scala
This patch reverts the previous change to support ONLY new style pings.
We want instead to support both new style and old style ones.
=> Bug 1344698 - Add support for both new and old style pings

README.md
Fix `yarn-client` deprecation warning and update scala version to 2.11
=> Update fat jar submission command

src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala
This changes the format of the addon_mapping.json
file to print both the default addon name and the
real addon id for a given hashed addon id. The new
format is:
{
"<hashed_id>" : {
"name" : "<addon default name>",
"id" : "<addon id>"
},
...
}
The old format was:
{
"<hashed_id>" : "<addon default name>",
...
}
=> Write the real addon id to the addon mapping

src/main/scala/com/mozilla/telemetry/views/HBaseMainSummaryView.scala
This is for a version bump we are doing Monday 5/8.
=> Update HBase job to use current MainSummary version

docs/longitudinal_examples.md
=> Change location of example notebooks

src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
Also change some 4-space indents to 2-space.
After 3 hours of trying to get a test to work... it just was not happening. I did test this manually with the sample heka file you sent.
=> Change int scalar types to IntegerType

src/main/scala/com/mozilla/telemetry/views/ClientCountView.scala
It wasn't downstream, so I missed it during my first pass.
=> Update client_count to use current main_summary version

src/main/scala/com/mozilla/telemetry/views/GeneralizedLongitudinal.scala
Need this for using subsets of input data. I was considering just creating views, but that clutters the namespace and this seems easier.
=> Add where clause to Generalized Longitudinal

src/main/scala/com/mozilla/telemetry/views/GenericLongitudinal.scala, src/test/scala/com/mozilla/telemetry/views/GenericLongitudinalTest.scala
I like this terminology better, and some people have been referring to it this way anyways.
=> Change generalized to generic

src/main/scala/com/mozilla/telemetry/views/GenericLongitudinal.scala
=> Fix date col usage in Generic Long

src/main/scala/com/mozilla/telemetry/views/ToplineSummaryView.scala, src/test/scala/com/mozilla/telemetry/ToplineSummaryViewTest.scala
[Bug 1364617 - Remove crash aggregates from ToplineSummary](https://bugzilla.mozilla.org/show_bug.cgi?id=1364617)
These aggregates aren't being shown on the executive dashboard, so this removes it.
=> Bug 1364617 - Remove crash aggregates from ToplineSummary

src/main/scala/com/mozilla/telemetry/views/GenericLongitudinal.scala, src/test/scala/com/mozilla/telemetry/views/GenericLongitudinalTest.scala
Basically added three new options to the CLI, as well as increasing test coverage to include options. These options put this code in line with the GenericCountView PR.
=> Generic Longitudinal updates

src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala, src/test/scala/com/mozilla/telemetry/MainSummaryViewTest.scala
Hmm, I can't ask @SamPenrose for a review. Feel free to take a look. The test fails without the fix, with the same error as bug 1368886.
=> Bug 1368886 - Fix Boolean UserPref null type

src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
I'll have a new airflow job just for this backfill.
=> Allow overwrite for main_summary

src/main/scala/com/mozilla/telemetry/views/ExperimentSummaryView.scala, src/test/resources/normandy_api_result.json, src/test/scala/com/mozilla/telemetry/ExperimentSummaryViewTest.scala
According to Osmose, pref rollouts *will* be a different action so this will work for our purposes
A note that I took actual output from the Normandy server for the test fixtures, but it's a public, unauthed API
=> Experiment main summary

src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala, src/test/scala/com/mozilla/telemetry/MainSummaryViewTest.scala
I think this is the last field that needs to be added for Bug 1362161.
=> Bug 1362161 - Add creationDate field

src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
Backfill was failing because of these.
=> Fix main_summary running on old data

src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala, src/test/scala/com/mozilla/telemetry/MainSummaryViewTest.scala
r? @mreid-moz - I'm going to submit a separate PR for the docs which have moved to another repo.
=> Bug 1372900 - add PLUGINS_INFOBAR_DISMISSED to main_summary

src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
=> Add TLS Histograms to main_summary

src/main/scala/com/mozilla/telemetry/views/QuantumRCView.scala
Job wasn't running without it. I need to investigate why, I've created bug 1375359 for that. In the meantime this fixes the issue and the job runs, without adding any significant time.
@mreid-moz, have you had time for anything but reviews lately?
=> Set mergeSchema option in Quantum RC View

src/main/scala/com/mozilla/telemetry/metrics/Histogram.scala, src/main/scala/com/mozilla/telemetry/metrics/Metric.scala, src/main/scala/com/mozilla/telemetry/metrics/MetricDefinition.scala, src/main/scala/com/mozilla/telemetry/metrics/Scalars.scala, src/main/scala/com/mozilla/telemetry/utils/MainPing.scala, src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala, src/test/resources/Scalars.yaml, src/test/resources/ShortHistograms.json, src/test/scala/com/mozilla/telemetry/MainSummaryViewTest.scala, src/test/scala/com/mozilla/telemetry/experiments/analyzers/HistogramAnalyzerTest.scala, src/test/scala/com/mozilla/telemetry/experiments/analyzers/ScalarAnalyzerTest.scala, src/test/scala/com/mozilla/telemetry/histograms/HistogramsTest.scala, src/test/scala/com/mozilla/telemetry/scalars/ScalarsTest.scala
This does two things:
1. Adds all process histograms for any histograms in the whitelist
2. Adds all process scalars
=> Add all process histograms and scalars to main_summary

build.sbt, src/main/scala/com/mozilla/telemetry/experiments/analyzers/MetricAnalyzer.scala, src/main/scala/com/mozilla/telemetry/experiments/statistics/PairwiseAggregateTests.scala, src/test/scala/com/mozilla/telemetry/experiments/analyzers/HistogramAnalyzerTest.scala, src/test/scala/com/mozilla/telemetry/experiments/analyzers/ScalarAnalyzerTest.scala
Not 100% satisfied with the design here re: how to call & append the statistical test results but it's been kind of hard to think while I've been at all-hands :P I'll probably revisit this as we add more stats.
=> Add Mann-Whitney U Test as first statistical test

src/main/scala/com/mozilla/telemetry/views/ExperimentAnalysisView.scala
Per our discussion -- adds logging so we have a slightly better idea of where things are failing in the experiment aggregate job
=> Add logging to ExperimentAnalysisView

src/main/scala/com/mozilla/telemetry/views/ExperimentAnalysisView.scala
The job was failing intermittently. We've seen this before on
consecutive spark jobs, for example, main_summary.
=> Bug 1387107 - Stop and start spark session between experiment runs

src/main/scala/com/mozilla/telemetry/ml/AMODatabase.scala, src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala
This also updates the AddonRecommender to make sure that
information bit is also reported into the addon mapping file
used to produce the results for the collaborative filter.
=> Add the "isWebextension" info to the AMODatabase

src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala, src/test/scala/com/mozilla/telemetry/views/LongitudinalViewTest.scala
Was in the neighborhood anyways.
=> Bug 1307187 - Add process scalars to longitudinal

src/main/scala/com/mozilla/telemetry/views/HBaseAddonRecommenderView.scala, src/test/scala/com/mozilla/telemetry/views/HBaseAddonRecommenderViewTest.scala
This PR adds a scala job that scans the main summary and feeds addon plus some other data into an HBase instance.
**Do not review yet**.
=> Add HBase view for the addon recommender

src/main/scala/com/mozilla/telemetry/views/ExperimentAnalysisView.scala
Silly fix, sigh.
I'd write a test but it wouldn't really be a test of our program logic, per se.
=> Merge schema when reading in parquet files for experiments analysis job

src/main/scala/com/mozilla/telemetry/experiments/analyzers/CrashAnalyzer.scala, src/main/scala/com/mozilla/telemetry/views/ExperimentAnalysisView.scala, src/test/scala/com/mozilla/telemetry/views/ExperimentAnalysisViewTest.scala
Note that the data for this isn't available yet :/ see https://bugzilla.mozilla.org/show_bug.cgi?id=1388351#c3.
=> Add crashes to experiment analysis view

src/main/scala/com/mozilla/telemetry/views/HBaseAddonRecommenderView.scala
Instead of applying a window function on the DataFrame containing all the columns we require, we apply it to a smaller DataFrame only containing the (client_id, subsession_start_date) for each ping in the  main_summary. We pick the most recent entry and perform a join with the DataFrame containing all the data we need to perform filtering.
Please note that this change will still make the job go OOM on Spark < 2.2.0 due to [SPARK-12837](https://issues.apache.org/jira/browse/SPARK-12837).
I already tried that for 2017-09-11 on a 5 nodes cluster running EMR 5.8.0 and it does not go OOM. See [the log](https://drive.google.com/a/mozilla.com/file/d/0B1RACVTBwZ94Z2NfVi10WG1FZE0/view?usp=sharing).
=> Fix the Addon HBase job from going OOM

src/main/scala/com/mozilla/telemetry/utils/ConsistentPartitioner.scala, src/main/scala/com/mozilla/telemetry/utils/CustomPartitioners.scala, src/main/scala/com/mozilla/telemetry/utils/package.scala, src/main/scala/com/mozilla/telemetry/views/ExperimentSummaryView.scala, src/main/scala/com/mozilla/telemetry/views/HeavyUsersView.scala, src/test/scala/com/mozilla/telemetry/utils/ConsistentPartitionerTest.scala, src/test/scala/com/mozilla/telemetry/views/HeavyUsersViewTest.scala
1. Joining on Sample ID
2. Removing `date`s data before running
3. Using consistent hashing as the partitioning scheme
=> Heavy users updates

src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
=> Bug 1397416 - Add histogram uptake to main summary

src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala, src/test/scala/com/mozilla/telemetry/views/LongitudinalViewTest.scala
I did confirm my added test raises the same error as I saw in production.
This change will take OS from the first ping for a client it finds
it from. It also applies the change to client_id and normalized_
channel, just in case.
This change also makes OS optional. Why is that?
1. Top-level OS field comes env/system/os/name [0]
2. env/system/os/name can be missing [1]
[0] https://github.com/mozilla-services/lua_sandbox_extensions/blob
/master/moz_telemetry/io_modules/decoders/moz_ingest/telemetry.lua#L213
[1] https://github.com/mozilla-services/mozilla-pipeline-schemas/
blob/master/schemas/telemetry/main/main.4.schema.json#L778
=> Bug 1402747 - Fix missing OS field

src/main/scala/com/mozilla/telemetry/views/HeavyUsersView.scala
Previously, the job grouped by client_id, sample_id, and profile_
creation_date. This was a problem, since a few clients had many
profile_creation_dates. These clients would cause the job to
explode (essentially, after a few days, the job would end up
with millions of rows on these clients, since it was a cross
product on each day due to the join on client_id).
Now we just take the first profile_creation_date and first sample_id.
This fixes the issue.
=> Require one row per client in heavy_users

src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala, src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
These won't run in Databricks otherwise.
=> Use Spark Session

src/main/scala/com/mozilla/telemetry/experiments/analyzers/CrashAnalyzer.scala, src/main/scala/com/mozilla/telemetry/experiments/analyzers/ExperimentAnalyzer.scala, src/main/scala/com/mozilla/telemetry/experiments/analyzers/MetricAnalyzer.scala, src/main/scala/com/mozilla/telemetry/experiments/analyzers/ScalarAnalyzer.scala, src/main/scala/com/mozilla/telemetry/experiments/analyzers/package.scala, src/main/scala/com/mozilla/telemetry/experiments/statistics/ComparativeStatistics.scala, src/main/scala/com/mozilla/telemetry/experiments/statistics/DescriptiveStatistics.scala, src/main/scala/com/mozilla/telemetry/views/ExperimentAnalysisView.scala, src/test/scala/com/mozilla/telemetry/experiments/analyzers/ExperimentAnalyzerTest.scala, src/test/scala/com/mozilla/telemetry/experiments/analyzers/HistogramAnalyzerTest.scala, src/test/scala/com/mozilla/telemetry/experiments/analyzers/ScalarAnalyzerTest.scala, src/test/scala/com/mozilla/telemetry/experiments/statistics/ComparativeStatisticsTest.scala, src/test/scala/com/mozilla/telemetry/experiments/statistics/DescriptiveStatisticsTest.scala
These are just the bare stats, no inference yet.
The PR looks big but there are only about 200 lines of actual changes -- the rest are tests :)
=> Add descriptive statistics and chi-square distance

src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala
Eventually we may add categorical histograms but... not today :)
=> Fix warning of unmatched CategoricalHistogram

src/main/scala/com/mozilla/telemetry/views/SyncEventView.scala, src/main/scala/com/mozilla/telemetry/views/SyncFlatView.scala, src/main/scala/com/mozilla/telemetry/views/SyncView.scala, src/test/scala/com/mozilla/telemetry/views/SyncViewTestPayloads.scala
See [bug 1410152 in bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1410152) for description.
=> Bug 1410152 - Handle android sync telemetry submitting wrong document version

README.md, build.sbt
fixes sbt assembly target to target/scala-2.11
fixes badge in readme
=> fixing sbt assembly target and badge

src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala, src/test/scala/com/mozilla/telemetry/views/MainSummaryViewTest.scala
First one to r+ wins dzeber's undying gratitude
=> Bug 1416915: Add browser.search.widget.inNavBar to userPrefsList

src/main/scala/com/mozilla/telemetry/views/HeavyUsersView.scala, src/test/scala/com/mozilla/telemetry/views/HeavyUsersViewTest.scala
Check for the date before the target date, rather than the last
date available in the dataset.
=> Fix existing-data-sensing code.

src/main/scala/com/mozilla/telemetry/experiments/analyzers/CrashAnalyzer.scala, src/main/scala/com/mozilla/telemetry/views/ExperimentAnalysisView.scala, src/test/scala/com/mozilla/telemetry/views/ExperimentAnalysisViewTest.scala
Tested, this works with the updated experiment_error_aggregates.
=> Experiment error aggregates

src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala
This PR does two things:
1. Removes the hack from Bug 1321424 which was a quick fix to prevent duplicate longitudinal runs, which we haven't run into since the Dockerflow migration. Instead the behavior was changed to delete any previously existing data before the run, which is closer to the overwrite logic we're using for main summary and other jobs recently
2. Sets the number of shuffle/output partitions to defaultParallelism (960 in the case of the 30 node cluster we're currently using), which will hopefully fix the errors for the last two runs, which are probably OOMs due to sorting in too-large partitions, and will potentially also speed up the job enough to finish under the timeout threshhold
Tested this on nightly pings for 20171230
=> Bug 1404715 - Longitudinal Fixes

src/main/scala/com/mozilla/telemetry/utils/DatasetComparator.scala, src/test/scala/com/mozilla/telemetry/utils/DatasetComparatorTest.scala
initially went with matching count and set of `document_id`s
=> Bug 1431458 - add util that validates test main_summary output against prod

.travis.yml
Adds the `backfill` branch for travis.
=> Add the backfill branch to .travis.yml

src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
alternative solution with less change
=> Bug 1399625 - limit file size in main_summary

src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala, src/test/scala/com/mozilla/telemetry/views/MainSummaryViewTest.scala
This is based off #377, commit 418abd5 is the relevant part here. Review should wait until #377 has landed.
=> Bug 1270183 - Add clock skew field

src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala, src/test/scala/com/mozilla/telemetry/views/MainSummaryViewTest.scala
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1438918)
To be rebased on #377
=>  Bug 1438918 - Add normalizedOSVersion to main_summary 

src/main/scala/com/mozilla/telemetry/utils/DatasetComparator.scala
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1444216)
This uses a single query to count all of the null values in each column. 
Tested on a 1% sample of main summary.
```
-bash-4.2$ time \
> spark-submit \
> --master yarn \
> --class com.mozilla.telemetry.utils.DatasetComparator \
> backfill-ms.jar \
> --date 20180101 \
> --data-path main_summary/v4 \
> --original-bucket net-mozaws-prod-us-west-2-pipeline-analysis/amiyaguchi/ms_test_2/original \
> --test-bucket net-mozaws-prod-us-west-2-pipeline-analysis/amiyaguchi/ms_test_2/final
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/mnt1/ -Xmx15000M -Xms1000M
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/mnt1/ -Xmx15000M -Xms1000M
=======================================================================================
BEGINNING JOB …
```
=> Bug 1444216 - Improve performance of null checking in DatasetComparator

src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala, src/test/scala/com/mozilla/telemetry/views/MainSummaryViewTest.scala
[buglink](https://bugzilla.mozilla.org/show_bug.cgi?id=1448463)
=> Bug 1448463 - Add browser.search.region to user-pref whitelist

src/main/scala/com/mozilla/telemetry/utils/DatasetComparator.scala
Also makes output more verbose by printing matches as well as differences
I think this makes the tool a bit more usable, and the `resultPath` option makes it so that we don't have to depend on sometimes-missing `println` output to confirm the results of the job.
=> Bug 1448160 - Add resultPath option to DatasetComparator

src/main/scala/com/mozilla/telemetry/utils/DatasetComparator.scala, src/test/scala/com/mozilla/telemetry/utils/DatasetComparatorTest.scala
and Bug 1453859 - make printing results optional
=> Bug 1449674 - Clean up DatasetComparator

README.md
This includes both dev and stage, in conjunction with
the telemetry-airflow README changes.
=> Add documentation about testing and deploying

build.sbt, java.policy, run-sbt.sh, src/main/scala/com/mozilla/telemetry/views/GenericLongitudinal.scala, src/test/scala/com/mozilla/telemetry/ml/AddonRecommenderTest.scala, src/test/scala/com/mozilla/telemetry/views/CrashAggregateViewTest.scala, src/test/scala/com/mozilla/telemetry/views/CrossSectionalViewTest.scala, src/test/scala/com/mozilla/telemetry/views/GenericLongitudinalTest.scala
https://github.com/mozilla/telemetry-batch-view/pull/426 was merged without sufficient testing. Reverting https://github.com/mozilla/telemetry-batch-view/commit/543ea848b3b8c6a5c797e8fc6b9100c9d0e35b72
=> Revert #426

build.sbt, src/main/scala/com/mozilla/telemetry/experiments/analyzers/ExperimentEngagementAnalyzer.scala, src/main/scala/com/mozilla/telemetry/views/ExperimentAnalysisView.scala, src/test/scala/com/mozilla/telemetry/views/ExperimentAnalysisViewTest.scala
Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1460090
Methodology: https://metrics.mozilla.com/protected/sguha/shield_bootstrap.html
~~I have not run a large-scale test of this yet, but did run on a single experiment_id in ATMO successfully.~~ Large-scale test was successful.
~~I need to add some better tests.~~ Tests added.
=> Bug 1460090 Experiment engagement aggregates

build.sbt, src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala, src/test/scala/com/mozilla/telemetry/views/LongitudinalViewTest.scala
This is currently running, I expect we'll know tomorrow whether setting the value at 5000 is small enough.
=> Bug 1468351 - Pre-filter client pings before partitioning in Longitudinal

src/main/scala/com/mozilla/telemetry/views/dau/DesktopDauView.scala, src/main/scala/com/mozilla/telemetry/views/dau/GenericDauTrait.scala, src/test/resources/log4j.properties, src/test/scala/com/mozilla/telemetry/views/dau/DesktopDauViewTest.scala, src/test/scala/com/mozilla/telemetry/views/dau/GenericDauConfTest.scala, src/test/scala/com/mozilla/telemetry/views/dau/GenericDauTraitTest.scala
Creates datasets that replace queries like `mau_dau_er_*` in [mozilla/stmo_core_product_metrics/health](https://github.com/mozilla/stmo_core_product_metrics/tree/master/health)
=> Bug 1469388 - Add generic dau view

src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
This makes MainSummary job fail if more than 0.5% records read were ignored (not deserialized properly).
Since we can get the ignore ration only after output is written, in case of failure output location will contain data. I'm not deleting it since the assumption is it will be overwritten anyway and it might come in handy for developers.
=> Bug 1477719 - Fail if too many records are ignored in Main Summary

src/main/scala/com/mozilla/telemetry/views/dau/DesktopActiveDauView.scala, src/main/scala/com/mozilla/telemetry/views/dau/GenericDauTrait.scala, src/test/scala/com/mozilla/telemetry/views/dau/DesktopActiveDauViewTest.scala, src/test/scala/com/mozilla/telemetry/views/dau/GenericDauConfTest.scala, src/test/scala/com/mozilla/telemetry/views/dau/GenericDauTraitTest.scala
=> Add view for active DAU

build.sbt
I don't recall if anyone objected to this in the team meeting when it was brought up, but I needed it today.
=> Bug 1478474 - Add ammonite to sbt

src/main/scala/com/mozilla/telemetry/experiments/analyzers/ExperimentEngagementAnalyzer.scala, src/main/scala/com/mozilla/telemetry/views/ExperimentAnalysisView.scala
Ran this successfully as a one-off for the experiment that has been failing the past few days, so I think this accomplishes what we need.
=> Bug 1497857 Reduce memory usage in ExperimentEngagementAnalyzer

GRAVEYARD.md
=> Add Pioneer Online News Dwell Time to graveyard

src/main/scala/com/mozilla/telemetry/views/ClientsDailyView.scala, src/test/scala/com/mozilla/telemetry/views/ClientsDailyViewTest.scala, src/test/scala/com/mozilla/telemetry/views/ClientsDailyViewTestHelpers.scala
Following up on #519 to add these fields to clients daily as well.
=> Bug 1525702 - Add "intl" fields to ClientsDailyView

project/build.properties, src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, src/main/scala/com/mozilla/telemetry/views/BatchJobBase.scala, src/test/scala/com/mozilla/telemetry/ml/AddonRecommenderTest.scala
Some notes:
* switching to clients_daily increases training dataset ~100x
* we should be able to run this daily (test runs were around 40 mins)
=>  Switch AddonRecommender to clients_daily 

src/main/scala/com/mozilla/telemetry/views/ClientsDailyView.scala, src/test/scala/com/mozilla/telemetry/views/ClientsDailyViewTestHelpers.scala
fixes [bug 1544092](https://bugzilla.mozilla.org/show_bug.cgi?id=1544092)
cc @jtg567
=> Bug 1544092 - aggregate sync_count_* with mean

src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala, src/test/scala/com/mozilla/telemetry/views/MainSummaryViewTest.scala
See https://bugzilla.mozilla.org/show_bug.cgi?id=1543408
=> Bug 1543408 Add user_pref_browser_search_region to MainSummaryView

src/main/scala/com/mozilla/telemetry/views/ClientsDailyView.scala, src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala, src/test/scala/com/mozilla/telemetry/views/MainSummaryViewTest.scala
See https://bugzilla.mozilla.org/show_bug.cgi?id=1550752
=> Bug 1550752 Add fxa_configured to MainSummary and ClientsDaily

src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala, src/test/scala/com/mozilla/telemetry/views/MainSummaryViewTest.scala
See https://bugzilla.mozilla.org/show_bug.cgi?id=1552940
=> Bug 1552940 Add disk type to MainSummaryView

src/main/scala/com/mozilla/telemetry/views/CrashSummaryView.scala
telemetry-airflow pr forthcoming...
=> Bug 1560996 - Bump crash summary version to v2

src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, src/main/scala/com/mozilla/telemetry/utils/package.scala
=> Support gcs in addition to s3 in AddonRecommender

src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala
needed for https://github.com/mozilla/telemetry-airflow/pull/749
cc @crankycoder
=> Read clients daily from gcs if necessary in AddonRecommender

src/main/scala/com/mozilla/telemetry/utils/package.scala, src/main/scala/com/mozilla/telemetry/views/ExperimentSummaryView.scala, src/test/scala/com/mozilla/telemetry/views/ExperimentSummaryViewTest.scala
and remove dropDuplicates because main summary no longer contains duplicates
=> Support non-s3 paths in ExperimentSummaryView

src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala
=> Add localCheckpoint to taar similarity
