mozilla/telemetry-batch-view

src/main/scala/DerivedStream.scala
src/main/scala/streams/Churn.scala
src/test/scala/ChurnTest.scala
src/test/scala/ParquetFile.scala

**DO NOT MERGE**
Just looking for feedback.  I set the output bucket in `src/main/resources/application.conf` to `telemetry-test-bucket`, and I am seeing the following error when I run this code:
```
<...snip...>
16/01/08 17:19:34 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 0 ms
16/01/08 17:19:37 INFO Executor: Finished task 35.0 in stage 4.0 (TID 47). 1165 bytes result sent to driver
16/01/08 17:19:37 INFO TaskSetManager: Starting task 40.0 in stage 4.0 (TID 52, localhost, PROCESS_LOCAL, 2170 bytes)
16/01/08 17:19:37 INFO Executor: Running task 40.0 in stage 4.0 (TID 52)
16/01/08 17:19:37 INFO TaskSetManager: Finished task 35.0 in stage 4.0 (TID 47) in 24141 ms on localhost (37/41)
16/01/08 17:19:37 INFO ShuffleBlockFetcherIterator: Getting 4 non-empty blocks out of 4 …
```

Add a derived data set to compute churn

---

src/test/scala/ParquetFile.scala

Quick fix to un-break the ParquetFile tests.
The getName function just returns the basename, while toString
returns a useful path.

Get the file path as a string correctly.

---

src/main/scala/streams/Churn.scala

Analyses may want to order submissions within a day.

Add the message timestamp as a parquet field.

---

src/main/scala/DerivedStream.scala
src/main/scala/streams/Churn.scala

Instead of extending `SimpleDerivedStream`, directly extend `DerivedStream`, and ignore the supplied list of S3 objects, instead fetching the file list for each day in the specified range.
Also repartition into 100 pieces to avoid huge numbers of tiny files on S3 which causes bad performance.
There are a few ugly hacks in here (including the hard-coding of `100` as the number of partitions). Feedback welcome.

Modify Churn to use fewer partitions

---

README.md
build.sbt

This changes the assembly jar filename from `telemetry-batch-view.jar` to `telemetry-batch-view-1.0.jar` (and will change when we bump the version in `build.sbt`).

Include version in assembly jar

---

src/main/scala/parquet/ParquetFile.scala
src/main/scala/streams/Longitudinal.scala

The longitudinal dataset has only a few hundred profiles per row group, which is detrimental for performance. This patch increases the number of profiles per row group while simultaneously reducing the memory footprint of the job, without which it wouldn't be possible to run on a typical c3.4xlarge cluster.
Furthermore, the number of cores per executor has to be reduced by 2x and the storage memory fraction has to be set to 0 when running the job, e.g.:
```
spark-submit --master yarn-client --executor-cores 8 --class telemetry.DerivedStream \
--conf spark.storage.memoryFraction=0 ./target/scala-2.10/telemetry-batch-view-1.1.jar \
--from-date 20151115 --to-date 20160213 Longitudinal
```
Note that even though the number of executors is halved, the time of the job reduces to about 2h over …

Pack more profiles in a row group.

---

src/main/scala/streams/Churn.scala

The name should be separated_by_underscores rather than camelCase.

Fix the S3 partition field name

---

src/main/scala/streams/Longitudinal.scala

Before, geoCountry would be omitted whenever geoCity is missing. However, :chutten mentioned that it's still useful to have geoCountry even this is the case.
The geoCountry/geoCity is set to an empty string because using nullables in arrays seems to expand the schema quite a bit. This seems to be a known issue with Avro.

Fix geoCountry generally being missing

---

src/main/scala/streams/Longitudinal.scala
src/test/scala/Longitudinal.scala

Ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1250889

Add additional fields of interest.

---

src/main/scala/streams/Longitudinal.scala

It seems to be related to a few JSON4s bugs, though I'm not sure exactly what triggers them.
Anyways, the fix is really simple and some test output with a small number of pings can be found here: https://console.aws.amazon.com/s3/home?region=us-west-2#&bucket=telemetry-test-bucket&prefix=longitudinal/v20160301/.

Fix deserialization error causing exceptions for threadHangStats.

---

src/main/scala/streams/Longitudinal.scala
src/main/scala/utils/Utils.scala
src/test/scala/Longitudinal.scala

It's kind of hacky, but it works!
All dates within real timezones are kept as-is. All dates outside are brought inside by adding/subtracting 12 hours.

Include the timezone, but normalize it if needed

---

src/main/scala/DerivedStream.scala

Also some bug numbers to make cross-referencing easier.

Add beta46-noapz experiment

---

README.md
src/main/scala/utils/Utils.scala

Utils was using integer division when it should use float division. As a result, the timezone 14:30, which is invalid, was truncated to timezone 14:00, which is valid.
Ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1258683

Fix timezone edge case that was incorrect due to integer division

---

src/main/scala/DerivedStream.scala
src/main/scala/streams/E10sExperiment.scala

The second beta46 experiment changed the format; there's now a system addon that sets environment/settings/e10sCohort.
This means we need a new flag in E10SExperiment that can handle this correctly, or a new class for it. This PR is an initial implementation, it probably still needs some more tests.

Add necessary fields for beta46 experiment 2

---

src/main/scala/streams/E10sExperiment.scala

The E10S experiment notebooks reject pings with mismatched e10s status, but we also want to do this at the derived stream level.
The previous PR had a bug where the test would never pass. This fixes it.

Fix cohort detection

---

src/main/scala/streams/E10sExperiment.scala

This is needed in order to split populations based on architecture and other build-rated values.

Add build field

---

.travis.yml

It looks like this is reducing the total [Travis run time](https://travis-ci.org/mozilla/telemetry-batch-view/builds/129172611 ) by ~2 minutes

Add caching of ivy dependencies to Travis setup

---

scripts/crash-rate-aggregates-watchdog.ipynb

The first commit adds a copy of [the watchdog used in moz-crash-rate-aggregates](https://github.com/mozilla/moz-crash-rate-aggregates/blob/9b3c80e1767208be5c95d0e8405872f4ff5549b7/crash-rate-aggregates-watchdog.ipynb) ([Bug 1275346](https://bugzilla.mozilla.org/show_bug.cgi?id=1275346)), while the second one makes it look for a _SUCCESS file instead of a partition folder ([Bug 1269725](https://bugzilla.mozilla.org/show_bug.cgi?id=1269725)).

Bug 1275346 add crash aggr watchdog

---

docs/CrashAggregateView.md
src/main/scala/views/CrashAggregateView.scala
src/test/scala/CrashAggregateViewTest.scala

This changes the source field for `activity date`  to either payload.info.subsessionStartDate or payload.crashDate, based on whether the the activity comes from a main ping or a crash ping.

Bug 1275146 - Use correct source field for activity date

---

src/main/scala/views/CrashAggregateView.scala

This is a resurrection of the code in https://github.com/mozilla/telemetry-batch-view/pull/70 which was backed out because it wasn't tested before merging.
I tested it manually on a sample of 100 messages and it seems to be working:
```
=======================================================================================
JOB COMPLETED SUCCESSFULLY FOR 2016-04-30T00:00:00.000+01:00
255 main pings processed, 5 pings ignored
135 crash pings processed, 0 pings ignored
=======================================================================================
```

Use the Telemetry lib instead of the custom, brittle  getRecords() function

---

src/main/scala/DerivedStream.scala
src/main/scala/SimpleDerivedStream.scala
src/main/scala/heka/Dataset.scala
src/main/scala/streams/Churn.scala
src/main/scala/streams/E10sExperiment.scala
src/main/scala/streams/Longitudinal.scala
src/main/scala/utils/S3.scala
src/main/scala/utils/Telemetry.scala
src/main/scala/views/MainSummaryView.scala
src/test/scala/DatasetTest.scala

The current way of accessing files on S3 is very ugly. This patch adds a simple way to fetch Heka files based on a set of filtering criteria on the dimensions, e.g.:
```scala
Dataset("telemetry")
.where("sourceName") {
case "telemetry" => true
}.where("sourceVersion") {
case "4" => true
}.where("docType") {
case "main" => true
}.where("appName") {
case "Firefox" => true
}.where("submissionDate") {
case date if date.startsWith("2016") => true
}.records()
```

Implement a flexible API to access Heka files on S3.

---

src/main/scala/com/mozilla/telemetry/heka/Dataset.scala
src/main/scala/com/mozilla/telemetry/utils/S3.scala
src/main/scala/com/mozilla/telemetry/utils/package.scala
src/main/scala/com/mozilla/telemetry/views/Churn.scala
src/main/scala/com/mozilla/telemetry/views/E10sExperiment.scala
src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala
src/test/scala/com/mozilla/telemetry/DatasetTest.scala

This patch makes the scanning of files on S3 about 13x faster on a c3.4xlarge, in doing so it decreases the run-time of the Longitudinal job by about 30 min (10%).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/87)

Parallelize Dataset implementation.

---

README.md
docs/CrashAggregateView.md
src/main/scala/com/mozilla/telemetry/views/ClientCountView.scala
src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala
src/main/scala/com/mozilla/telemetry/views/E10sExperiment.scala
src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala

This library was removed from the project dependencies in
https://github.com/mozilla/telemetry-batch-view/commit/c7c8cc4bcedbc3b7c343fc1490eb775be5dba4c2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/86)

Bug 1282405 - stop using com.typesafe.config

---

src/main/scala/com/mozilla/telemetry/utils/S3.scala
src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
src/test/scala/com/mozilla/telemetry/DatasetTest.scala

Per Bug 1282758, having the _metadata and _SUCCESS files in non-leaf
directories breaks Spark's partition discovery in our current version.
The problem is fixed in Spark 2.0, but until then, we work around it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/88)

Get rid of metadata that breaks partition discovery.

---

src/main/scala/com/mozilla/telemetry/heka/HekaFrame.scala
src/test/scala/com/mozilla/telemetry/DatasetTest.scala

S3Object opens a connection which is not freed even if the object is garbage
collected so it has to be explicitely closed in order to liberate the connection
to the pool.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1285127.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/92)

Close S3Objects after reading them.

---

build.sbt
src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala
src/main/scala/com/mozilla/telemetry/ml/NaNRegressionEvaluator.scala

This patch uses matrix factorization to recommend add-ons. The training
phase outputs a set of artifacts in JSON files which can be used from other
languages to compute a list of suggested add-ons from a given set of add-ons.
Once the model has been trained, computing recommendations requires 
just a couple of matrix multiplications. See `AddonRecommender.recommend` 
for a Scala implementation of how to do so.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/90)

Implement an add-on recommendation engine.

---

src/main/scala/com/mozilla/telemetry/utils/package.scala
src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala
src/test/scala/com/mozilla/telemetry/LongitudinalTest.scala

Adding windowsUBR and windowsBuildNumber to longitudinal dataset.
I'm not sure how uncamelize will behave with "windowsUBR". Is there a way to generate an example dataset locally? I followed the instructions on the README, but needed AWS credentials.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/96)

Bug 1286305: Add new system.os fields to longitudinal dataset

---

src/main/scala/com/mozilla/telemetry/views/E10sExperiment.scala

After bug 1218576, this is where child histograms could be.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/98)

Bug 1287101 - Pass the new `processes` structure through

---

build.sbt
src/main/scala/com/mozilla/telemetry/ml/AMODatabase.scala
src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala

This changes the addon recommender to fetch the addon database from addons.mozilla.org. We use the dumped information to prune commercial, unreviewed, privated or, in general, unlisted addons before training the model.
We also use the dumped information to get the addon name from the reported default locale, instead of relying on data coming from the clients.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/97)

Train with addon ids

---

src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala
src/test/scala/com/mozilla/telemetry/CrossSectionalViewTest.scala

Bug 1286573 - Create cross-sectional parquet dataset
This view only calculates a simple modal country and discards the data
after counting the number of rows. From this platform, we can save the
data to S3 and begin adding more metrics to meet the project
requirements.
There was a significant amount of troubleshooting required to get to
this stage. Accordingly, I'd like to keep this commit as the simplest
example of working with a Dataset instead of a Dataframe.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/105)

Add a basic CrossSectionalView with a single metric

---

src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala
src/test/scala/com/mozilla/telemetry/CrossSectionalViewTest.scala

Bug 1298123: Refactor dataset classes so they do not use case classes
Spark datasets can only be generated from classes which implement the
Product interface. We would usually use case classes for this purpose,
but case classes are limited to 22 fields. This change implements a
class to bypass this restriction.
This limit is removed in scala 2.11. Accordingly, this change should
only be a stop gap until we can upgrade our spark clusters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/108)

Replace case class to bypass the 22 field limit

---

src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala

Bug 1298119 - Write example XSec dataset to S3
Apparently, writing to S3 was broken with non-backwards compatible
changes to the api. Including an older version of the JAR fixes my write
errors. Without this jar I get a NoSuchMethodError error from AWS.
Reference article:
http://deploymentzone.com/2015/12/20/s3a-on-spark-on-aws-ec2/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/107)

Make CrossSectionalView write to S3

---

build.sbt
src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala
src/main/scala/com/mozilla/telemetry/ml/NaNRegressionEvaluator.scala
src/main/scala/com/mozilla/telemetry/views/Churn.scala
src/main/scala/com/mozilla/telemetry/views/ClientCountView.scala
src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala
src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala
src/main/scala/com/mozilla/telemetry/views/E10sExperiment.scala
src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala
src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
src/test/scala/com/mozilla/telemetry/ParquetFile.scala

I plan to enlist help moving our jobs to Spark 2.0. I don't expect big issues but I think it makes sense that each owner schedules his jobs with Spark 2.0 through Airflow and makes sure that it works as expected. 
I will file some bugs in the next days and provide one or more examples of how to schedule a Scala job from Airflow with Spark 2.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/111)

Move package to Spark 2.0

---

src/main/scala/com/mozilla/telemetry/utils/Aggregation.scala
src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala
src/test/scala/com/mozilla/telemetry/AggregationTest.scala
src/test/scala/com/mozilla/telemetry/CrossSectionalViewTest.scala

Moved XSec generator functions into class methods and constructors.
Separated Aggregate object into it's own context. Split aggregation into
it's own package
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/109)

Refactor agg functions to a separate package

---

src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala

This is no longer available in Spark 2.0. See [this issue](https://issues.apache.org/jira/browse/SPARK-10063) and [this discussion](http://dev.sortable.com/spark-directparquetoutputcommitter/) for more info.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/115)

Remove DirectParquetOutputCommitter

---

docs/E10SExperiment.md

The command to build the E10s dataset makes reference to the explicit scala version in its args. Updating for future reference, as it changed with the update to Spark 2.0.
It also bears mentioning that this now needs to be run on an EMR-5.0.0 cluster supporting Spark 2.0. I wasn't sure if it was worth adding that to the readme (eg. updating the link to a.t.m.o). If this will soon become the default for our clusters, it may not be necessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/119)

Update explicit scala version in jar path (E10s dataset)

---

src/main/scala/com/mozilla/telemetry/views/SyncView.scala
src/test/scala/com/mozilla/telemetry/SyncViewTest.scala
src/test/scala/com/mozilla/telemetry/SyncViewTestPayloads.scala

This is a first cut that seems to "work", for some definitions of "work".
Alot of code was cargo-culted from MainSummaryView - I'm not sure how much
is relevant here. Some of the new parsing code I added is almost certainly
not idiomatic scala.
There are some tests. Some .json test files are parsed and their contents
verified. One of these payloads is also round-tripped through a local parquet
file and the content verified.
I also had a test that added a .heka file I grabbed of s3 and verified I could
parse it, but I felt that had little value as I couldn't actually verify the
contents. The commit where I removed it is at:
> https://github.com/mhammond/telemetry-batch-view/commit/ad40720d09d1717660bfc0ea140e67e80998f1b1
and I can reinstate that if you like.
Note that the code is handling …

Create a derived parquet dataset for the sync ping.

---

README.md
src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala
src/test/scala/com/mozilla/telemetry/LongitudinalTest.scala

The scalars section was added by bug 1282091, which
landed on July 2016. Pings before that date don't
have the scalars section. If we have a ping with
the missing section among the pings for a client,
the longitudinal view drops all the data from that
client, if if newer pings have the scalar section.
This patch prevents that from happening.
Bonus: this also adds some documentation about
running this code on Windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/124)

Get scalar data from clients with old pings

---

src/main/scala/com/mozilla/telemetry/heka/Dataset.scala
src/test/scala/com/mozilla/telemetry/DatasetTest.scala

This is an educated guess based off of https://github.com/mozilla/python_moztelemetry/pull/86.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/125)

Bug 1302264 - Use metadata_prefix for looking up dataset schema

---

docs/available_datasets.md
docs/longitudinal_examples.md
scripts/wiki_to_md.sh

Step 1 of the documentation reboot is checking in existing dataset documentation. Once this is merged, we can deprecate and redirect the wiki pages to this repo. 
Adds two key pages of documentation from the wiki, Longitudinal Examples
and Available Datasets. Tool documentation will likely live elsewhere.
@fbertsch, can you take a look?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/128)

Add documentation from wiki to docs directory

---

src/main/scala/com/mozilla/telemetry/utils/Aggregation.scala
src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala
src/test/scala/com/mozilla/telemetry/CrossSectionalViewTest.scala

This commit gives us feature parity with the python prototype by
bcolloran:
https://github.com/mozilla/bcolloran_spark/blob/master/perClientDataPrep/cross-sectional%20data%20table%20%282016-07-14%29%20-%20deduped%20clientIds.ipynb
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/127)

Add remaining columns to cross sectional database

---

.sbtopts
src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala
src/test/scala/com/mozilla/telemetry/CrossSectionalViewTest.scala

Avoid having to manually set environment variables for memory-related JVM parameters by updating them in the .sbtopts file.
This addresses the "GC Limit" OOM problem and possibly others.
Also reduce Spark verbosity in a couple of tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/132)

Fix memory problems via .sbtopts so that (quieter) tests can be run.

---

docs/MainSummary.md
src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
src/test/scala/com/mozilla/telemetry/MainSummaryViewTest.scala

Add a new field to MainSummaryView for the pref value of
`dom.ipc.processCount`. If that pref has not been changed from the
default value it will appear as null.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/139)

Bug 1304104 - Add "dom.ipc.processCount" to main_summary

---

src/main/scala/com/mozilla/telemetry/views/AddonsView.scala

Since the addons data was added later, early date partitions do
not have the addon columns, so the auto-detected schema doesn't
make them available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/141)

Read only the given day's main_summary data

---

src/main/scala/com/mozilla/telemetry/avro/JSON2Avro.scala
src/test/scala/com/mozilla/telemetry/LongitudinalTest.scala

Bug 1274008: In longitudinal, there are probably-incorrect results in
settings.user_prefs
In the `Longitudinal` table, `settings.userPrefs` is parsed as a
`Map[String, String]`. However, `userPrefs` has non-string valued fields:
`browser.zoom.full` and `browser.startup.page`, for example. This change
allows these Boolean, Integer, Decimal, and Double types to be parsed as Strings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/142)

Allow cast from JSON [Numeric|Bools] to String

---

src/main/scala/com/mozilla/telemetry/views/SyncView.scala
src/test/scala/com/mozilla/telemetry/SyncViewTest.scala
src/test/scala/com/mozilla/telemetry/SyncViewTestPayloads.scala

This updates the sync ping view to handle changes to the sync ping as well as adds support for recording new data.
This encompasses the work for [bug 1314864](https://bugzilla.mozilla.org/show_bug.cgi?id=1314864). Specific set of data changes, in no order:
1. The device constellation for a user, [from bug 1308567](https://bugzilla.mozilla.org/show_bug.cgi?id=1308567).
2. Bookmark validation data, [from bug 1267917](https://bugzilla.mozilla.org/show_bug.cgi?id=1267917) and is present in a very small number of cases. (This is currently something like 1 sync per day, for 10% of nightly users who have fewer than 100 bookmarks, although those numbers are subject to change).
3. Reporting an updated error type added in [Bug 1312320](https://bugzilla.mozilla.org/show_bug.cgi?id=1312320).
4. The …

Bug 1314864 - Update SyncView to contain new updated and new fields from the sync ping.

---

src/main/scala/com/mozilla/telemetry/histograms/Histogram.scala
src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala
src/test/scala/com/mozilla/telemetry/LongitudinalTest.scala

Bug 1313151 - Remove opt-in histograms from longitudinal dataset
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/148)

Remove opt-in histograms from Longitudinal View

---

src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala
src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala

'main' is the right identifier to use instead of 'browser'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/157)

Bug 1325974 - Use processType='main' to identify main crashes

---

docs/MainSummary.md
src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
src/test/scala/com/mozilla/telemetry/MainSummaryViewTest.scala

Since we're getting events in nightly and aurora now, we need to start presenting them for analysis.
I'm not 100% sure that Main Summary is the right place for this, but if we're processing main pings anyway adding a new column shouldn't be a huge deal, if I understand how Parquet works correctly. My next step after this would be to pull out an events dataset much like we do with addons.
Extracting the parameters is kind of ugly since events are a list of lists instead of a list of objects, so we can't use json4s's case class extractors. I attempted to write a custom deserializer for an Events case class but it ended up just looking like this anyway, just in a different file. Open to suggestions for how to get this looking more idiomatic -- working with variable-length heterogeneous lists …

Add events to MainSummaryView

---

.gitignore
.travis.yml
README.md
build.sbt
project/build.properties
src/test/resources/log4j.properties
src/test/scala/com/mozilla/telemetry/views/HBaseMainSummaryViewTest.scala

This patch labels HBase tests as slow and disables their execution when
running `sbt test`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/162)

Mark HBase tests as slow.

---

src/main/scala/com/mozilla/telemetry/views/CrashSummaryView.scala
src/test/resources/crash_ping_indented.json
src/test/scala/com/mozilla/telemetry/CrashSummaryViewTest.scala

The first version of CrashSummaryView is based on what's required by CrashAggregates. More fields can be easily added modifying the various case classes. ~It's still missing some tests for `CrashSummary.transformPayload`, but~ it's ready for a first look. I wrote a few tests to cover the few lines of logic in `transformPayload`, the compiler should cover the rest. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/161)

Bug 1316860 - Add CrashSummary batch view

---

src/main/scala/com/mozilla/telemetry/utils/MainPing.scala
src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
src/test/scala/com/mozilla/telemetry/MainSummaryViewTest.scala

This patch adds a new column called `attribution` along with the related tests for [bug 1331082](https://bugzilla.mozilla.org/show_bug.cgi?id=1331082). These fields will be used in retention analysis.
r? @sunahsuh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/165)

Bug 1331082 - Add stub attribution fields to main summary

---

src/main/scala/com/mozilla/telemetry/histograms/Histogram.scala
src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala
src/test/scala/com/mozilla/telemetry/LongitudinalTest.scala

This change also makes it easy to add new histogram endpoints in the
future. Just add a path and suffix to histogramLocations or
keyedHistogramLocations. This whitelist updates both the parsing code
and the dataset schema.
I prototyped a version of this code which would remove the whitelist by
automatically scanning for new keys under "payload.processes". However,
we have to add these new keys/suffixes to the dataset schema.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-batch-view/155)

Add content histograms to longitudinal view

---

.travis.yml
build.sbt
project/plugins.sbt
src/main/scala/com/mozilla/telemetry/views/AddonsView.scala
src/test/scala/com/mozilla/telemetry/AddonsViewTest.scala

Some tests stopped running after the introduction of the slow tag which
caused the coverage to drop.

Fix coverage status.

---

src/main/scala/com/mozilla/telemetry/views/SyncView.scala

This patch repartitions the dataframe before writing to s3 to prevent
client (Spark, Presto)  parquet decoding errors. This patch also enable
overwriting old data, which makes this fix available by applying a
backfill to a date.
The sync_summary dataset generated by SyncView occassionally has invalid
parquet data in `engines.list.element.name` (column 14). The two
occurances that were caught and fixed with this patch are where
`submission_date_s3` is is equal to `20161204` and `20161208`.
The specific decode error is `java.lang.IllegalArgumentException:
Reading past RLE/BitPacking stream`. It was found that repartitioning
the data before writing out to s3 fixes decoding errors (for 2/2 cases).
An issue with parquet encoding is suspected, but there are many
potential causes.
This patch has …

Bug 1329023 - Fix parquet decode errors in SyncView via repartition

---

build.sbt
src/main/scala/com/mozilla/telemetry/views/ClientCountView.scala
src/test/scala/com/mozilla/telemetry/ClientCountViewTest.scala

See https://bugzilla.mozilla.org/show_bug.cgi?id=1339308 for context.
This PR adds the top 3 distributions, which account for nearly 70%
of values.

Add top distribution ids to client_count dataset

---

.travis.yml

If this worked correctly we'll only have the PR build and not the push build on this PR

Restrict travis push builds to master branch only

---

src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
src/test/scala/com/mozilla/telemetry/MainSummaryViewTest.scala

I realized as I was working on pulling Events out into their own dataset that the schema application test for events in main summary didn't actually run the test as I thought because of lazy evaluation. Running it properly caught a few bugs in the schema format, which this PR fixes.

Bug 1339130: Fix events output to conform to schema

---

src/main/scala/com/mozilla/telemetry/views/CrashSummaryView.scala
src/test/resources/crash_ping_indented.json
src/test/scala/com/mozilla/telemetry/CrashSummaryViewTest.scala

The CEP recently changed the name/place where the ping content is stored.

Bug 1342817 - Use `submission` instead of `payload` to get ping content

---

src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
src/test/scala/com/mozilla/telemetry/MainSummaryViewTest.scala

[Bug 1331702](https://bugzilla.mozilla.org/show_bug.cgi?id=1331702)
Wow64 is used to tell the CPU architecture of Windows machines apart. This adds `is_wow64` field to main summary.

Bug 1331702 - Add is_wow64 to main summary

---

src/main/scala/com/mozilla/telemetry/utils/Events.scala
src/main/scala/com/mozilla/telemetry/views/MainEventsView.scala
src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
src/main/scala/com/mozilla/telemetry/views/SyncEventView.scala
src/test/scala/com/mozilla/telemetry/EventsTest.scala
src/test/scala/com/mozilla/telemetry/MainSummaryViewTest.scala
src/test/scala/com/mozilla/telemetry/SyncEventViewTest.scala

- Moves Events out of MainSummaryView into a utility class
- Adds a job to output Sync Events into a flattened view
No timestamp column yet since I feel like it'd be confusing if we don't use the session start date, which we'll add once it's added to the sync ping.

Sync events view

---

src/main/scala/com/mozilla/telemetry/views/CrashSummaryView.scala
src/test/resources/crash_ping_indented.json
src/test/scala/com/mozilla/telemetry/CrashSummaryViewTest.scala

When during a profile's life do crashes happen? And what effect might they
have on the churn of users who might only just have started trying Firefox
for the first time?
Currently testing this on a day's data.

Bug 1336488 - Add profile.creationDate to CrashSummaryView

---

src/main/scala/com/mozilla/telemetry/histograms/Histogram.scala
src/main/scala/com/mozilla/telemetry/scalars/Scalars.scala
src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala
src/test/resources/Histograms.json
src/test/resources/Scalars.yaml
src/test/resources/ShortHistograms.json
src/test/scala/com/mozilla/telemetry/CrossSectionalViewTest.scala
src/test/scala/com/mozilla/telemetry/LongitudinalTest.scala
src/test/scala/com/mozilla/telemetry/histograms/HistogramsTest.scala
src/test/scala/com/mozilla/telemetry/scalars/ScalarsTest.scala

This is similar to my previous PR but without the per-process stuff. As such we won't be able to actually create this dataset yet, but the ability is there. I just wanted to use the scalar and histogram parts I created in here for some main_summary work.
Also, now the options are: an opt-out only dataset, or an opt-out and opt-in dataset. No more of the confusing "just opt-in" parts.

Bug 13490813 - Create Prerelease Longitudinal

---

src/main/scala/com/mozilla/telemetry/views/SyncEventView.scala
src/test/scala/com/mozilla/telemetry/SyncEventViewTest.scala

It's not practical for the redash queries to pull this data out of the sync ping (for numerous and unfortunate reasons).
(cc @DavisMTL who has been trying to work around this being missing all day)

Bug 1359268 - Add the target device OS and version to the sync event telemetry when possible.

---

src/main/scala/com/mozilla/telemetry/views/ToplineSummary.scala

This column was previously added for compatibility with the original `v4_reformat.py` script. This was implemented incorrectly (it should have used yyyy-MM-dd) and is redundant because of report_start.
The topline_dashboard etl job will handle the date field instead.

Remove `date` column from ToplineSummaryView

---

src/main/scala/com/mozilla/telemetry/views/ToplineSummaryView.scala
src/test/scala/com/mozilla/telemetry/ToplineSummaryViewTest.scala

This naming convention is more consistent with other classes in this project. This also fixes failing airflow jobs that used ToplineSummaryView instead of ToplineSummary.

Rename ToplineSummary to ToplineSummaryView

---

src/main/scala/com/mozilla/telemetry/views/ToplineSummaryView.scala

This reduces the number of partitions before writing to disk. The default number of partitions is 200, which results in partitions that are 3kb in size.

Reduce the final number of partitions in ToplineSummary from 200 to 1

---

src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala

Makes `channels` option default to all channels

Bug 1361819 - Missing "esr" and "Other" data in recent longitudinal tables

---

src/main/scala/com/mozilla/telemetry/utils/udfs.scala
src/main/scala/com/mozilla/telemetry/views/GeneralizedLongitudinal.scala
src/test/scala/com/mozilla/telemetry/views/GeneralizedLongitudinalTest.scala

This will allow us to make Longitudinal-type datasets out of any parquet datasets. I'll be using this for the mobile ones to begin with. With Presto now supporting lambda-expressions, these datasets will be easy-to-use in STMO.
The basic idea here is to give it a dataset name, a grouping column, and any number of ordering columns. Most datasets will be grouped by client_id, and ordered by submission_date or activity_date.
Ideas for more test cases are welcome!

Add generalized longitudinal job

---

src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala
src/test/scala/com/mozilla/telemetry/LongitudinalTest.scala

This change adds session_start_date to the longitudinal dataset.
Note that this change removes the calls to `return` and consequentially
changes the behavior of the code in the case of missing
`subsession_start_date` values. However, these values are not missing in
practice, and this appears to be an undefined edge case currently.

Bug 1329541: ... `session_start_date` is null for all records

---

src/main/scala/com/mozilla/telemetry/views/GenericLongitudinal.scala

This will allow us to use any spark function in the `where` clause.
After this we can set this up with the mobile jobs :)

Make all spark functions available to Generic Long

---

src/main/scala/com/mozilla/telemetry/views/GenericCountView.scala
src/test/scala/com/mozilla/telemetry/views/GenericCountViewTest.scala

This job takes an input table and creates a dataset that has
counts across a set of dimensions. These counts are implemented
as hlls.
Testing is exactly the client_count tests. I've moved as much of the usage of options to be within the testable code as possible.

Add generic counting job

---

src/main/scala/com/mozilla/telemetry/views/ToplineSummaryView.scala

The `topline_dashboard` job [relies on column ordering for conversion when applying a schema](https://github.com/mozilla/python_mozetl/blob/master/mozetl/topline/topline_dashboard.py#L180). The upstream ToplineSummary should stay somewhat consistent with this schema.
This also fixes the `crashes` column, which gets saved as an IntegerType. This is incompatible with the LongType.

Preserve column types and ordering on ToplineSummary

---

src/main/scala/com/mozilla/telemetry/utils/MainPing.scala
src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
src/test/resources/ShortHistograms.json
src/test/scala/com/mozilla/telemetry/MainSummaryViewTest.scala

Currently this only includes Linear and Exponential opt-out hists.
The format is essentially exactly what we recieve from the client,
see the case class for the schema.

Automatically add hists to main_summary

---

src/main/scala/com/mozilla/telemetry/views/AddonsView.scala
src/test/scala/com/mozilla/telemetry/AddonsViewTest.scala

Oops, we missed the part about adding these fields to the `Addons` data in the mentioned bug.

Bug 1360177 - Add new fields to the Addons dataset

---

src/main/scala/com/mozilla/telemetry/experiments/analyzers/HistogramAnalyzer.scala
src/main/scala/com/mozilla/telemetry/experiments/analyzers/package.scala
src/main/scala/com/mozilla/telemetry/utils/package.scala
src/main/scala/com/mozilla/telemetry/views/ExperimentAnalysisView.scala
src/test/scala/com/mozilla/telemetry/experiments/analyzers/HistogramAnalyzerTest.scala

Much smaller PR than last time: this is the first iteration of the experiment metric aggregation and analysis job based on Main Summary and Datasets.
Currently, this only aggregates the whitelisted histograms in main summary. The next PR will include scalar aggregation, and the one after that probably summary stats.

Add working histogram aggregation job

---

src/main/scala/com/mozilla/telemetry/views/GenericCountView.scala

Should fix the current problem, but it doesn't explain why Spark is creating the metadata dirs before the actual data starts loading.
This hasn't been tested, can do tomorrow, but is the same as most of our other jobs now.

Make generic count view overwrite

---

src/main/scala/com/mozilla/telemetry/views/GenericCountView.scala

Instead of reprocessing all data every week we want to update the Quantum RC, having it partitioned means that I can update it weekly with only the most recent data, assuming the schema doesn't change. Eventually we can do this with the other counts as well.
This shouldn't affect end users as all queries are using `WHERE` and `GROUP BY`, which will still be fine with the partitions, even if two rows in separate partitions have the same values for all dimensions.

Add partition option to Generic Count view

---

src/main/scala/com/mozilla/telemetry/views/ExperimentSummaryView.scala
src/test/scala/com/mozilla/telemetry/ExperimentSummaryViewTest.scala

This also includes a generic `dedupe()` function available for
all DataFrames, so we can easily call: `df.dedupe()` to remove
any duplicates.

Bug 1375560 - Dedupe experiments view

---

src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
src/test/scala/com/mozilla/telemetry/views/MainSummaryViewTest.scala

There was a single test for NULL. No code specific to client_count.

Bug 1309598 - Remove Loop metrics from main_summary & client_count datasets

---

src/main/scala/com/mozilla/telemetry/views/SyncView.scala
src/test/scala/com/mozilla/telemetry/views/SyncViewTest.scala
src/test/scala/com/mozilla/telemetry/views/SyncViewTestPayloads.scala

Hi! We added OS data to the Sync ping in https://bugzilla.mozilla.org/show_bug.cgi?id=1373093, but I don't think it's in the `sync_summary` table yet. This adds the base fields from [`TelemetryEnvironment#_getOSData`](http://searchfox.org/mozilla-central/rev/31311070d9860b24fe4a7a36976c14b328c16208/toolkit/components/telemetry/TelemetryEnvironment.jsm#1463-1467) as columns to `sync_summary`.

Bug 1375353 - Add OS info to the Sync summary view

---

src/main/scala/com/mozilla/telemetry/experiments/analyzers/Aggregators.scala
src/main/scala/com/mozilla/telemetry/experiments/analyzers/ScalarAnalyzer.scala
src/main/scala/com/mozilla/telemetry/metrics/Histogram.scala
src/main/scala/com/mozilla/telemetry/metrics/Metric.scala
src/main/scala/com/mozilla/telemetry/metrics/Scalars.scala
src/main/scala/com/mozilla/telemetry/utils/MainPing.scala
src/main/scala/com/mozilla/telemetry/views/ExperimentAnalysisView.scala
src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala
src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
src/test/scala/com/mozilla/telemetry/experiments/analyzers/HistogramAnalyzerTest.scala
src/test/scala/com/mozilla/telemetry/experiments/analyzers/ScalarAnalyzerTest.scala
src/test/scala/com/mozilla/telemetry/metrics/HistogramsTest.scala
src/test/scala/com/mozilla/telemetry/metrics/ScalarsTest.scala
src/test/scala/com/mozilla/telemetry/utils/MainPingTest.scala
src/test/scala/com/mozilla/telemetry/views/ExperimentAnalysisViewTest.scala
src/test/scala/com/mozilla/telemetry/views/LongitudinalViewTest.scala
src/test/scala/com/mozilla/telemetry/views/MainSummaryViewTest.scala

I included a bit of the reverted code, since I needed it for testing. I stripped out everything to do with the derived scalars, which we can talk about re-adding down the line (with some changes).
Look at the commit for a summary of changes. Kept Histograms.definitions backwards compatible with LongitudinalView.

Bug 1378804 - Add Process Metrics to Experiment Analysis View

---

src/main/scala/com/mozilla/telemetry/experiments/analyzers/ExperimentAnalyzer.scala
src/main/scala/com/mozilla/telemetry/experiments/analyzers/MetricAnalyzer.scala
src/main/scala/com/mozilla/telemetry/views/ExperimentAnalysisView.scala
src/test/scala/com/mozilla/telemetry/experiments/analyzers/ExperimentAnalyzerTest.scala
src/test/scala/com/mozilla/telemetry/experiments/analyzers/HistogramAnalyzerTest.scala
src/test/scala/com/mozilla/telemetry/views/ExperimentAnalysisViewTest.scala

This adds a row to the experiment aggregates output which includes ping and client count as "Statistics" objects for each branch/subgroup
Required for mozilla/experiments-viewer#155

Add metadata (client and ping count) row to experiment aggregates

---

src/main/scala/com/mozilla/telemetry/views/ExperimentAnalysisView.scala
src/test/scala/com/mozilla/telemetry/views/ExperimentAnalysisViewTest.scala

The metadata output had a bug where each experiment was outputting metadata *every* experiment, not just its own, because I passed in the unfiltered dataset. Whoops.
cc @robhudson

Fix experiment metadata output

---

src/main/scala/com/mozilla/telemetry/utils/package.scala
src/main/scala/com/mozilla/telemetry/views/ExperimentAnalysisView.scala
src/main/scala/com/mozilla/telemetry/views/ExperimentSummaryView.scala
src/test/scala/com/mozilla/telemetry/views/ExperimentSummaryViewTest.scala

Welp. I'm gonna guess at least a few of the problems with the experiment jobs are due to hard-coding local spark mode.

Fix spark mode on experiment jobs

---

src/main/scala/com/mozilla/telemetry/experiments/analyzers/ExperimentAnalyzer.scala

The experiment aggregates job is still timing out, so I think it's worth at least giving this a try

Try using approxCountDistinct to reduce processing time

---

src/main/scala/com/mozilla/telemetry/experiments/analyzers/ExperimentAnalyzer.scala

This reverts commit 07a5a6795efe0476fef1db499b11f854571f367e.
Might as well go back to real counts now. Note this isn't an *exact* revert since there was an unused import that I deleted in the original commit (`org.apache.spark.sql.functions.sum`)

Revert "Try using approxCountDistinct to reduce processing time"

---

src/main/scala/com/mozilla/telemetry/views/QuantumRCView.scala
src/test/scala/com/mozilla/telemetry/views/QuantumRCViewTest.scala

Experiment data should be seen using mission control or the
experiment viewer. This data should be used to monitor the
health of the quantum rollout.
Note that this change requires a schema bump.

Remove experiment_id/branch from QuantumRCView

---

src/main/scala/com/mozilla/telemetry/utils/MainPing.scala
src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
src/test/resources/ScalarsActiveTicks.yaml
src/test/scala/com/mozilla/telemetry/utils/MainPingTest.scala
src/test/scala/com/mozilla/telemetry/views/MainSummaryViewTest.scala

Bug 1382002 - Added and used MainPing.getScalarByName to access a scalar value from the payload, which if available, is supplemented for the original measurement. Currently being used for active_ticks. Includes tests.
@sunahsuh please review! :)

Activeticks fallback

---

src/main/scala/com/mozilla/telemetry/views/ExperimentSummaryView.scala
src/test/resources/normandy_api_result.json
src/test/scala/com/mozilla/telemetry/views/ExperimentSummaryViewTest.scala

This PR updates the experiment summary job to:
- Add a list of excluded recipes (first use is to exclude the screenshots release rollout)
- Include opt-out studies per [bug 1395362](https://bugzilla.mozilla.org/show_bug.cgi?id=1395362)
Unfortunately, opt-out studies have the slug in a different field than pref rollouts so that adds a bit of not-so-pretty munging.
Briefly, I've removed the "action" filter from the normandy url that we're pulling down so we're not getting just pref-flip experiments, normalized the slug/name fields, added opt-out studies to the allowed actions filter and added an excluded experiments list.

Update normandy recipe eligibility in ExperimentSummaryView

---

src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
src/test/scala/com/mozilla/telemetry/views/MainSummaryViewTest.scala

This field is required for the TAAR project and should not
be used for other purposes. See bug 1390814.
This makes use of the soon to be deprecated "addonDetails"
field that contains the list of the user's addons. It will
then populate the "disabled_addon_ids" column with the ids
of the addons that are in "addonDetails" but not in "activeAddons".
This field will go away after addon recommendation for FF57
are no longer needed.

Add a temporary list of disabled addon ids to main_summary

---

src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala

Anthony, this fixes the last S3 upload to make sure that the AMO dump is uploaded to the correct "file". It was mistakenly uploading to the "publicBucket". I've also renamed "publicS3prefix" to "latestS3prefix".

Save the AddonRecommender AMO dump to the right location

---

src/main/scala/com/mozilla/telemetry/utils/SyncPingConversion.scala
src/main/scala/com/mozilla/telemetry/views/SyncFlatView.scala
src/test/scala/com/mozilla/telemetry/views/SyncFlatViewTest.scala
src/test/scala/com/mozilla/telemetry/views/SyncViewTest.scala

Ideally I'd like for my patch for [Bug 1390320](https://bugzilla.mozilla.org/show_bug.cgi?id=1390320) to land first, but I'm getting it up without waiting, since it is not a small change (although I think the github diff viewer is making it look bigger than it is) and it wouldn't really surprise me that much if it were a little controversial. Once that's available, I'll probably change SyncFlatView's loop body around a bit to take advantage of it.
Since the github diff doesn't seem to capture this well, most of the code in SyncPingConversion.scala previously lived in SyncView.scala.
This also addresses a very small issue ([Bug 1389233](https://bugzilla.mozilla.org/show_bug.cgi?id=1389233)), where android and iOS will write outgoing arrays as an object. This is a bug in them that is being …

Bug 1381641 - Implement a sync view that flattens sync engine data

---

src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
src/test/scala/com/mozilla/telemetry/views/MainSummaryViewTest.scala

Turns out I was looking up the field in the wrong data structure: `payload` is not the ping payload, but rather the message payload. I've changed this accordingly and I'm re-generating the dataset in a test bucket.

Fix the MainSummaryView to correctly find addonDetails

---

src/main/scala/com/mozilla/telemetry/views/HBaseAddonRecommenderView.scala
src/test/scala/com/mozilla/telemetry/views/HBaseAddonRecommenderViewTest.scala

This fields contains the list of addon ids that were disabled and are not reported in `active_addons`. See
bug 1390814.

Add the "disabled_addons_ids" field to the TAAR HBase

---

src/main/scala/com/mozilla/telemetry/metrics/Histogram.scala
src/main/scala/com/mozilla/telemetry/utils/MainPing.scala
src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
src/test/resources/ShortHistograms.json
src/test/scala/com/mozilla/telemetry/views/MainSummaryViewTest.scala

Categorical histograms will show a Map[String, Integer] rather
than the Map[Integer, Integer] we've shown for all other
histograms.

Bug 1397913 - Allow categorical histograms in Main Summary

---

src/main/scala/com/mozilla/telemetry/views/HBaseAddonRecommenderView.scala
src/test/scala/com/mozilla/telemetry/views/HBaseAddonRecommenderViewTest.scala

This additionally extends the test coverage with a
sample full ping to make sure all fields are
reported.

Properly add "disabled_addons_ids" to HBase

---

src/main/scala/com/mozilla/telemetry/experiments/analyzers/HistogramAnalyzer.scala
src/main/scala/com/mozilla/telemetry/experiments/analyzers/MetricAnalyzer.scala
src/main/scala/com/mozilla/telemetry/experiments/analyzers/ScalarAnalyzer.scala
src/main/scala/com/mozilla/telemetry/metrics/Histogram.scala
src/test/scala/com/mozilla/telemetry/experiments/analyzers/HistogramAnalyzerTest.scala
src/test/scala/com/mozilla/telemetry/experiments/analyzers/ScalarAnalyzerTest.scala

- Adds a method to histogram definitions returning its valid bucket values
- Validates experiments data before aggregation to filter out negative values and validate incoming buckets
Closes mozilla/experiments-viewer#225 and mozilla/experiments-viewer#260

Validate experiments data before aggregating

---

src/main/scala/com/mozilla/telemetry/views/RetentionView.scala
src/test/scala/com/mozilla/telemetry/views/RetentionViewTest.scala

[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1381840)
This PR is used in conjunction with [mozilla/python_mozetl #133](https://github.com/mozilla/python_mozetl/pull/133) to generate a 1 day Firefox retention dataset.
The mozetl script will preprocess the data in the following stages:
1. Convert `new_profile_ping_parquet` to a subset of `main_summary_v4`
2. Join `new_profile` with `main_summary` and select the subset for the retention period
3. Build a select expression for cleaning and derived columns and apply the transformation
4. Write the cleaned intermediate data into HDFS
This job will carry out the aggregation of the final data, and store the data to the final output location.
As opposed to previous versions of `retention_dev` which use the `GenericCountView`, …

Bug 1381840 - Add 1 day Firefox retention view using HLL

---

build.sbt
src/main/scala/com/mozilla/telemetry/ml/AMODatabase.scala
src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala
src/main/scala/com/mozilla/telemetry/utils/package.scala
src/test/scala/com/mozilla/telemetry/ml/AMODatabaseTest.scala
src/test/scala/com/mozilla/telemetry/ml/AddonRecommenderTest.scala

This PR adds _basic_ test coverage for the `AMODataset` and the `AddonRecommender` scala objects. Long due, I know

Add test coverage for the AddonRecommender

---

src/main/scala/com/mozilla/telemetry/utils/SyncPingConversion.scala
src/test/scala/com/mozilla/telemetry/views/SyncViewTest.scala
src/test/scala/com/mozilla/telemetry/views/SyncViewTestPayloads.scala

I think this also slightly cleans up the sync ping code, but it's still pretty gnarly (sorry).

Bug 1409861 - Handle sync pings that have os information at top level

---

src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala

The AMODatabase init needs to happen before we get the SparkContext,
otherwise the job will fail due to all the workers being idle.

Move AMODatabase init before getting the SparkContext

---

src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala

In order to support to query the total user count of WebVR, I would like to add WEBVR_USERS_VIEW_IN, an enumerated histogram, to the whitelist.

Add WEBVR_USERS_VIEW_IN to histogramsWhitelist

---

src/main/scala/com/mozilla/telemetry/views/ExperimentSummaryView.scala
src/test/scala/com/mozilla/telemetry/views/ExperimentSummaryViewTest.scala

While we wait for mozilla/normandy#804, this is a workaround that should allow us to exclude definitely concluded experiments while staying backfill-friendly by checking the recipe's last updated date. This way, we might get some false positives (concluded experiments that were, for some reason, updated after being disabled) but we'll never have false negatives.
This should significantly speed up both jobs since we have quite a few concluded experiments at this point.

Excluded concluded experiments from ExperimentSummaryView

---

src/main/scala/com/mozilla/telemetry/utils/Events.scala
src/main/scala/com/mozilla/telemetry/views/MainEventsView.scala
src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
src/test/scala/com/mozilla/telemetry/utils/EventsTest.scala
src/test/scala/com/mozilla/telemetry/views/MainEventsViewTest.scala
src/test/scala/com/mozilla/telemetry/views/MainSummaryViewTest.scala

- Adds event extraction from content and dynamic processes in main summary (note: we're sticking the process name into the map_values field due to the schema evolution bug for nested objects)
- Moves the process name into a top-level field in the events table
- Not related to the bug, but since I was looking at it: adds the "experiments" block to the events table

Bug 1344259: Support for content and addon events

---

src/main/scala/com/mozilla/telemetry/experiments/analyzers/HistogramAnalyzer.scala
src/main/scala/com/mozilla/telemetry/experiments/analyzers/MetricAnalyzer.scala
src/main/scala/com/mozilla/telemetry/experiments/analyzers/ScalarAnalyzer.scala
src/main/scala/com/mozilla/telemetry/experiments/statistics/DescriptiveStatistics.scala
src/main/scala/com/mozilla/telemetry/metrics/Histogram.scala
src/main/scala/com/mozilla/telemetry/metrics/Metric.scala
src/main/scala/com/mozilla/telemetry/metrics/Scalars.scala
src/main/scala/com/mozilla/telemetry/views/ExperimentAnalysisView.scala
src/test/scala/com/mozilla/telemetry/experiments/analyzers/HistogramAnalyzerTest.scala
src/test/scala/com/mozilla/telemetry/experiments/analyzers/ScalarAnalyzerTest.scala
src/test/scala/com/mozilla/telemetry/views/ExperimentAnalysisViewTest.scala

This includes implementations of bootstrapped confidence intervals for both histograms and scalars but only turns them on for scalars in the job since the current histogram implementation is too slow to be pragmatically useful.
Briefly, the metric analyzer is responsible for providing resampled aggregates to the DescriptiveStatistics class, which merely runs the statistic on each aggregate, sorts the results and uses the simple percentile method to return the confidence interval.
The histogram resampler uses the built-in spark sample-with-replacement method, which is effective but slow.
The scalar resampler, on the otherhand, distributes resampling into separate spark tasks for each node and therefore is able to run much faster since we can resample directly from the aggregated histogram. …

Confidence intervals

---

src/main/scala/com/mozilla/telemetry/views/ExperimentAnalysisView.scala

The job is unfortunately timing out (on one particular experiment, it looks like -- the experiments before that are running pretty quickly) so I'm turning off bootstrapped CIs for now

Don't run bootstrapped CIs on scalars by default

---

src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala

Subtle bug with the new docType filtering where the `case` variable was shadowing and causing all docTypes to match.

Fix the docType filter

---

src/main/scala/com/mozilla/telemetry/views/HeavyUsersView.scala

Use Dataset operations to check the existence of data for "yesterday".
This is an attempt to work around the following error raised from [here](https://github.com/mozilla/telemetry-batch-view/blob/7d2d7a9176e87a625298fb8fe6a1b77729e5f9d0/src/main/scala/com/mozilla/telemetry/views/HeavyUsersView.scala#L250):
```
Exception in thread "main" java.lang.UnsupportedOperationException: Only code-generated evaluation is supported.
at org.apache.spark.sql.catalyst.expressions.objects.Invoke.eval(objects.scala:118)
at org.apache.spark.sql.catalyst.expressions.InterpretedPredicate$$anonfun$create$2.apply(predicates.scala:38)
at org.apache.spark.sql.catalyst.expressions.InterpretedPredicate$$anonfun$create$2.apply(predicates.scala:38)
at org.apache.spark.sql.execution.datasources.PartitioningAwareFileC …
```

Use Dataset API instead of DataFrame.

---

src/main/scala/com/mozilla/telemetry/experiments/analyzers/HistogramAnalyzer.scala
src/test/scala/com/mozilla/telemetry/experiments/analyzers/HistogramAnalyzerTest.scala

This fixes the ExperimentAnalysisView failures over the weekend -- basically, we have a ping or two where the inner map in a keyed histogram is null, for whatever reason, which was an unhandled issue. I've only been able to find two instances of this underlying issue in the main_summary in the column that was throwing this error (`histogram_parent_fx_urlbar_selected_result_index_by_type`) since 11/24 (when the job started failing with this error.) Since the incidence is small, I decided to just discard those pings.

Fix null pointer exception from specific client

---

src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala

to reduce individual file size
I added `document_id` to the columns we reparititon by, because if only increase the number for repartition then there's no effect, and I _think_ `document_id` is supposed to be unique per ping.

Bug 1399625 - reduce main_summary parquet file size

---

src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala

I believe this is causing the recent failures of main_summary - repartitioning to only 4 partitions seems likely to be blowing up a few of the workers.

Restore behaviour prior to #363

---

src/main/scala/com/mozilla/telemetry/utils/SyncPingConversion.scala
src/main/scala/com/mozilla/telemetry/views/SyncEventView.scala
src/test/scala/com/mozilla/telemetry/views/SyncEventViewTest.scala

[Relevant bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1432282). We plan on adding event telemetry for additional platforms soon, and so we're getting this done in advance.
I don't know if I need to bump `SyncEventView.schemaVersion` to `"v2"` for this, please let me know either way.
Thanks.

Bug 1432282 - Add fields from sync-ping/payload/os to the sync event telemetry table

---

build.sbt
src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
src/test/scala/com/mozilla/telemetry/views/MainSummaryViewTest.scala

I've added some methods for extracting nullable types from JValues. I liked the concise notation of `JValue.extractOpt[T].orNull` as opposed to the 2 line match statement. 
I ended up putting these methods into an extension class that makes it easy to add and modify methods. These are apparently treated as static method calls once it's been compiled/jit'ed, so they should be fairly fast. [1] On the other-hand, I'm not entirely sure how fast the json4s `extract` methods are compared to pattern matching since it's a generic method. [2]
I might try out the different cases (original, implicit class + pattern matching, implicit class + extract) and see if it makes a significance difference on runtime.
[1] http://docs.scala-lang.org/sips/completed/value-classes.html
[2] …

Use consistent interface for unwrapping nullable JValues

---

src/main/scala/com/mozilla/telemetry/views/SyncEventView.scala

Firefox Android sends pings with `appName: "Fennec"`.
Let's remove that filter on the SyncEventView and bring it in line with the other views.

Bug 1442326 - Do not filter Android sync event pings anymore

---

src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala
src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala
src/main/scala/com/mozilla/telemetry/views/GenericLongitudinal.scala
src/test/scala/com/mozilla/telemetry/views/CrashAggregateViewTest.scala
src/test/scala/com/mozilla/telemetry/views/CrossSectionalViewTest.scala
src/test/scala/com/mozilla/telemetry/views/LongitudinalViewTest.scala
src/test/scala/com/mozilla/telemetry/views/MainEventsViewTest.scala
src/test/scala/com/mozilla/telemetry/views/SyncViewTest.scala

This removes all remaining cases where SparkContext was explicitly created.
From now on, context is always accessed via session (and it's created via `getOrCreateSparkSession` util).

Bug 1395364 - Remove explicit SparkContext creation, use standard SparkSession utility instead

---

src/main/scala/com/mozilla/telemetry/views/ExperimentSummaryView.scala

Waiting for confirmation from Dave Zeber that it's safe to merge this in, but this experiment is causing the downstream experiment analysis job to fail (we're up to 2B+ cumulative pings in this experiment) and the story seems to be that it's safe to ignore it since analysis has concluded on this (pending Zeber's approval)

Add search composition experiment to excluded experiments

---

src/main/scala/com/mozilla/telemetry/utils/udfs.scala
src/main/scala/com/mozilla/telemetry/views/ClientsDailyView.scala
src/test/scala/com/mozilla/telemetry/views/ClientsDailyViewTest.scala
src/test/scala/com/mozilla/telemetry/views/ClientsDailyViewTestPayloads.scala

rewrite from python to scala to take advantage of user defined
aggregate functions, which are a java-only construct.
adds experiments column to replace experiments_daily dataset
changes from activity_date to submission_date

Bug 1431777 - Move Clients Daily out of python_mozetl

---

src/main/scala/com/mozilla/telemetry/utils/udfs.scala
src/test/scala/com/mozilla/telemetry/views/ClientsDailyViewTestPayloads.scala

backfill revealed a missing test case that was breaking the AggSearchCounts udaf

Fix handling of null search counts in clients daily

---

build.sbt
src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala

[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1450079)
The `--alignment` option is an integer representing a multiple of
defaultParallelism. If this is set, then the number of partitions will
be `alignment*sc.defaultParallelism`.
The number of documents in the first-shutdown ping is much smaller than main pings. The number of input partitions is `total document size / 268 MB`. This means the default tuning for moztelemetry and MainSummaryView will lead to poor performance on smaller document sets. This improves the performance with a smaller set of machines in the cluster (10 vs 25) on a large dataset, or a smaller dataset with a larger number of machines (first-shutdown instead of main). 
The option preserves the current behavior, but it would marginally improve MainSummary run …

Bug 1450079 - Add option to align number of input partitions

---

src/main/resources/addon/Scalars.yaml
src/main/scala/com/mozilla/telemetry/metrics/Histogram.scala
src/main/scala/com/mozilla/telemetry/metrics/Metric.scala
src/main/scala/com/mozilla/telemetry/metrics/Scalars.scala
src/main/scala/com/mozilla/telemetry/utils/MainPing.scala
src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala
src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
src/test/scala/com/mozilla/telemetry/metrics/ScalarsTest.scala
src/test/scala/com/mozilla/telemetry/utils/MainPingTest.scala
src/test/scala/com/mozilla/telemetry/views/LongitudinalViewTest.scala
src/test/scala/com/mozilla/telemetry/views/MainSummaryViewTest.scala

- Creates a new Scalars.yaml for Addon probes
- Incorporate DefaultProcess and AllowedProcesses for pings

Allow Addon scalar definitions in MainSummary

---

.travis.yml

This will support the quick-development use-case. Tests cannot
be skipped on tagged releases or master.
For example, if an engineer is working on a branch, and wants
to test out her changes using Airflow, they would need to build
the artifact and push it to s3 using a non-master branch. With
tests, that could take upwards of 1 hour -- with [skip-tests],
it should take under 5 minutes.

Add ability to skip tests

---

src/main/scala/com/mozilla/telemetry/views/pioneer/PioneerOnlineNewsDedupe.scala

We were well into the v2 launch before we realized that clients were sending us duplicate data -- lots of it (nearly 11B entries before, 239.5M after deduplication). This job deduplicates each entry, and retains metadata from the ping where the entry first appeared.

Add Online News log entry deduplication job

---

.travis.yml

The use-case for this feature is small changes that do not
necessarily need to be tested on stage, such as adding new
histograms to `main_summary`.
Simply include the string [auto-deploy] to make it so.

Add ability to auto-deploy

---

README.md
build.sbt
docs/CrashAggregateView.md
java.policy
run-sbt.sh
src/main/scala/com/mozilla/telemetry/views/GenericLongitudinal.scala
src/test/scala/com/mozilla/telemetry/ml/AddonRecommenderTest.scala
src/test/scala/com/mozilla/telemetry/views/CrashAggregateViewTest.scala
src/test/scala/com/mozilla/telemetry/views/CrossSectionalViewTest.scala
src/test/scala/com/mozilla/telemetry/views/GenericLongitudinalTest.scala

Support for hyphen-separated key names was dropped in sbt 1.0.0;
see https://www.scala-sbt.org/1.x/docs/sbt-1.0-Release-Notes.html#sbt+1.0.0
Also updates to the Spark version used by current default EMR in ATMO.

Versions update

---

build.sbt
src/test/scala/com/mozilla/telemetry/views/CrashAggregateViewTest.scala

For the following invocation:
./run-sbt.sh "testOnly *CrashAggregateViewTest"
runtime is 18 seconds with the lazy val.
Previously, this test took on order 5 minutes to run,
recreating the fixture for each individual call.

Add test duration logging and cache CrashAggregateView test fixture

---

.travis.yml
README.md
build.sbt
src/test/scala/com/mozilla/telemetry/experiments/analyzers/HistogramAnalyzerTest.scala
src/test/scala/com/mozilla/telemetry/experiments/analyzers/ScalarAnalyzerTest.scala
src/test/scala/com/mozilla/telemetry/experiments/statistics/DescriptiveStatisticsTest.scala
src/test/scala/com/mozilla/telemetry/tags/Tags.scala
src/test/scala/com/mozilla/telemetry/views/ClientsDailyViewTest.scala
src/test/scala/com/mozilla/telemetry/views/ExperimentAnalysisViewTest.scala

This PR reduces the runtime for CI from > 30 minutes to ~12 minutes by splitting testing work into parallel jobs and moving deployment to a separate "stage" of the build.
See an example of the layout of jobs and associated runtimes in https://travis-ci.org/mozilla/telemetry-batch-view/builds/385852363
This PR consists of adding Scalatest tags in the Scala source and a significant refactoring of the .travis.yml in order to use those tags to define separate jobs.
We also add a little bit of test fixture cleanup to reduce duplicated work.

Bug 1417571 - Improve test times via parallel Travis builds

---

.travis.yml

We were trying to build an uberjar and stage in S3,
but that requires encrypted env vars that aren't avaialable to
builds on forks, so we need to make the assembly and deploy stages conditional.

Fix problem that caused CI on forks to fail

---

build.sbt

This brings back in the Spark version update merged in #426 and subsequently backed out.
It also updates several other libraries to more recent (most recent where possible) versions.

Spark to 2.3.0 and update other dependencies

---

Dockerfile

This should make startup a bit faster and it will avoid the
problem on TravisCI where parallel jobs all hit bintray at the
same time, leading to throttling and intermittent failed jobs.

Use new base image that has sbt baked in

---

build.sbt

https://github.com/mozilla/telemetry-batch-view/pull/434
updated versions that changed the interface for Avro and caused
Longitudinal to fail.

Roll back avro dependency versions

---

src/main/scala/com/mozilla/telemetry/views/MainEventsView.scala
src/test/scala/com/mozilla/telemetry/views/MainEventsViewTest.scala

As mentioned in mozilla/telemetry-streaming#149, this is the update to main ping events output to match the new schema from events ping output. The only really interesting part is the new session_start_time field, which matches the format of the session_start_time payload field in the events ping.

Update Main Events schema to match event ping events

---

src/main/scala/com/mozilla/telemetry/views/ExperimentSummaryView.scala
src/test/scala/com/mozilla/telemetry/views/ExperimentSummaryViewTest.scala

Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1473641
The 'pref-hotfix-tls-13-avast-rollback' experiment has _much_ higher enrollment
than any other experiment in the past month.
It turned on on 6/28 with ~4 million appearances, which ballooned to 61M by 7/2.
This is at least an order of magnitude higher than any other experiment.
I'm pretty certain the problem we're hitting is that ExperimentSummaryView
is partitioning by experiment_id when writing with no cap on how
large a partition is, so it's trying to accumulate all 62M records
on a single node before writing out an object.
If we apply maxRecordsPerFile as we do on MainSummaryView,
then I think we'll be good.

Bug 1473641 Set maxRecordsPerFile in ExperimentsSummaryView

---

src/main/scala/com/mozilla/telemetry/views/ExperimentSummaryView.scala

We were seeing step failures again on this job with what looked like OOMs. It looks like a high-population experiment is the culprit. Two fixes here: ignore experiments tagged as high volume, and don't repartition by experiment_id (which is unbalanced anyway and most of the machines were probably just sitting idle most of the time) -- I'm coalescing down to 10 partitions instead which should keep all the executors busy but keep the number of files from exploding too badly.

Bug 1476038: Fix experiment summary (again)

---

build.sbt
src/main/scala/com/mozilla/telemetry/experiments/analyzers/ExperimentEngagementAnalyzer.scala
src/main/scala/com/mozilla/telemetry/experiments/statistics/StatisticalComputation.scala
src/main/scala/com/mozilla/telemetry/utils/ColumnEnumeration.scala
src/main/scala/com/mozilla/telemetry/utils/udfs.scala
src/main/scala/com/mozilla/telemetry/views/ExperimentAnalysisView.scala
src/test/scala/com/mozilla/telemetry/experiments/statistics/StatisticalComputationTest.scala
src/test/scala/com/mozilla/telemetry/utils/ColumnEnumerationTest.scala
src/test/scala/com/mozilla/telemetry/views/ExperimentAnalysisViewTest.scala

This adds retention metrics and refactors the analyzer to use fewer bare strings and instead rely on enumerations of column definitions.
I've run this code on recent data via EMR. See retention metric example at the bottom of:
https://dbc-caf9527b-e073.cloud.databricks.com/#notebook/19306

Bug 1474703 Add retention metrics to experiments_aggregates

---

src/main/scala/com/mozilla/telemetry/views/ExperimentSummaryView.scala
src/test/scala/com/mozilla/telemetry/views/ExperimentSummaryViewTest.scala

Adds three options for faster dev runs of experiments summary view and downstream tasks:
- `sample-id`, to restrict main summary input to a single sample id
- `experiment-limit`, to restrict the number of eligible experiments to explode over
- `row-limit`, to restrict the number of total input rows

Experiments summary dev options

---

src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala
src/test/scala/com/mozilla/telemetry/ml/AddonRecommenderTest.scala

This replaces the hardcoded blacklist and replaces it with an S3 loaded whitelist for TAAR addons.
The logic in getAddonData has been inverted to assert that an addonId is contained in the whitelist instead of not within a blacklist.
cc/ @mlopatka

TAAR: Removed the hardcoded blacklist 

---

src/main/scala/com/mozilla/telemetry/utils/MainPing.scala
src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
src/test/resources/ShortHistograms.json
src/test/scala/com/mozilla/telemetry/views/MainSummaryViewTest.scala

Previously, we allowed Flag histograms (but not count), and they
were just stored as histograms (a map of buckets and their counts).
These two histogram types should get special treatment, since
at their heart they are scalars. This change allows people to
add count and flag histograms, but stores them as scalars.
Note that to do so requires a bit of processing of the histogram,
where previously we just stored whatever we found there. So for
example, a flag histogram with value 2 in the 0 bucket will be
a null, since that is not a valid representation. If we stored
that as a histogram, we would find just {0: 2}.
Finally we have one flag histogram which cannot be converted.
A new list of histogram-represented histograms is added,
and if a probe is present in that list it's exact `values` …

Bug 1485682 - Scalarized Count and Flag histograms

---

scripts/test_run.sh
src/main/scala/com/mozilla/telemetry/views/AddonsView.scala
src/main/scala/com/mozilla/telemetry/views/BatchJobBase.scala
src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala
src/main/scala/com/mozilla/telemetry/views/CrashSummaryView.scala
src/main/scala/com/mozilla/telemetry/views/ExperimentAnalysisView.scala
src/main/scala/com/mozilla/telemetry/views/ExperimentSummaryView.scala
src/main/scala/com/mozilla/telemetry/views/GenericCountView.scala
src/main/scala/com/mozilla/telemetry/views/GenericLongitudinal.scala
src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala
src/main/scala/com/mozilla/telemetry/views/MainEventsView.scala
src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
src/main/scala/com/mozilla/telemetry/views/QuantumRCView.scala
src/main/scala/com/mozilla/telemetry/views/RetentionView.scala
src/main/scala/com/mozilla/telemetry/views/SyncEventView.scala
src/main/scala/com/mozilla/telemetry/views/SyncFlatView.scala
src/main/scala/com/mozilla/telemetry/views/SyncView.scala
src/test/scala/com/mozilla/telemetry/views/BatchJobBase.scala

[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1484341)
This adds a base class that has some context on whether to run `spark.stop`, as well as a helper for implementing backfills within the class. I tried to make changes with the least amount of invasion.
Here is a table with some information about how our jobs use input fields and dates. 
| View name           | input date fields | output date format | built-in backfill |
|---------------------|-------------------|--------------------|-------------------|
| Addons              | to/from           | nodash             | yes               |
| ClientsDaily        | date              | nodash             | no                |
| CrashAggregates     | to/from           | dash               | yes               |
| CrashSummary …

Bug 1484341 - Add a base class to telemetry-batch-view

---

src/main/scala/com/mozilla/telemetry/views/BatchJobBase.scala
src/main/scala/com/mozilla/telemetry/views/SyncEventView.scala
src/main/scala/com/mozilla/telemetry/views/SyncFlatView.scala
src/main/scala/com/mozilla/telemetry/views/SyncView.scala

[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1487902)
The crash summary and sync views are currently failing due to changes in the base options. This PR sets the bucket value as not required and removes the conflicting options from the sync view. Having an optional bucket means that current jobs may fail with run-time errors if poorly specified.
I will post confirmation from manual runs of this patch on ATMO.

Bug 1487902 - Fix bucket options in CrashSummary and Sync views

---

build.sbt
scripts/test_run.sh
src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala
src/main/scala/com/mozilla/telemetry/utils/SyncPingConversion.scala
src/main/scala/com/mozilla/telemetry/utils/package.scala
src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala
src/main/scala/com/mozilla/telemetry/views/ExperimentSummaryView.scala
src/main/scala/com/mozilla/telemetry/views/GenericCountView.scala
src/main/scala/com/mozilla/telemetry/views/GenericLongitudinal.scala
src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala
src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
src/main/scala/com/mozilla/telemetry/views/QuantumRCView.scala
src/test/scala/com/mozilla/telemetry/utils/UtilsTest.scala
src/test/scala/com/mozilla/telemetry/views/ExperimentSummaryViewTest.scala
src/test/scala/com/mozilla/telemetry/views/LongitudinalViewTest.scala
src/test/scala/com/mozilla/telemetry/views/SyncFlatViewTest.scala

[bug link](Bug 1458356)
This removes `joda-time` and the scala wrapper `nscala_time` from this repo. I tested the changes against `scripts/test_run.sh` which runs jobs with defaults and times out after a minute. If our jobs are going to fail at the entrypoint, they usually do it around the 40 second mark.

Bug 1458356 - Migrate jodatime usage in telemetry-batch-view to java.time API

---

GRAVEYARD.md

Per the discussion in the team meeting, starts the graveyard doc with heavy users as the first entry

Add graveyard doc

---

src/main/scala/com/mozilla/telemetry/utils/udfs.scala
src/main/scala/com/mozilla/telemetry/views/ClientsDailyView.scala
src/test/scala/com/mozilla/telemetry/views/ClientsDailyViewTest.scala
src/test/scala/com/mozilla/telemetry/views/ClientsDailyViewTestHelpers.scala

My test is failing because `None` values are being implicitly converted to zeros somewhere -- I'm confused about why this is happening but I think it's probably acceptable. Do you see a way to avoid it?

Aggregate keyed scalars by summing values by key

---

src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala

This is the target of the WebRender experiment. Per https://bugzilla.mozilla.org/show_bug.cgi?id=1495152, it is not consistently set for nightly users, so we need to filter pings for enrolled users by the actual value of the pref.

Add WebRender preference to main_summary

---

src/main/scala/com/mozilla/telemetry/views/ExperimentSummaryView.scala

This failed twice with timeouts yesterday, so I'm finally getting around to fixing it. This is the job that creates the `experiments` dataset, which has been timing out on the fetch to the Normandy dataset. I ran the method manually and it works fine (although i didn't go as far as introducing latency)

Bug 1500929: Increase timeout on fetch from normandy api

---

src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
src/test/scala/com/mozilla/telemetry/views/MainSummaryViewTest.scala

I named these fields verbosely so they would be compatible with [bug 1476630](https://bugzilla.mozilla.org/show_bug.cgi?id=1476630) if we tackle that in the future.
Another slightly weird thing is that doing `.extractOpt[List[String]]` means that any missing fields will result in an empty list in the output record rather than `null` as we normally do.

Bug 1525702 - Add "intl" fields

---

src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
src/test/scala/com/mozilla/telemetry/views/MainSummaryViewTest.scala

Add a new field to count the zero bucket, since accumulating false
in this histogram has a particular meaning. From the description:
The number of times the click-to-activate notification was shown:
false: shown by in-content activation
true: shown by location bar activation

Bug 1526278 - Fix PLUGINS_NOTIFICATION_SHOWN

---

src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala

Adds `browser.launcherProcess.enabled` to main_summary for pref-flip study.

add launcherProcess pref to main_summary

---

src/main/scala/com/mozilla/telemetry/views/ClientsDailyView.scala

bigquery gets mad when loading decimal fields with any precision other than `38,9`

Set decimal precision in clients_daily for bigquery compatibility

---

src/main/scala/com/mozilla/telemetry/views/ClientsDailyView.scala
src/main/scala/com/mozilla/telemetry/views/dau/GenericDauTrait.scala

reduce the precision from 37 to 35 for BigQuery compatibility, but keep the scale at `6` to prevent silent invalid data caused by bad schema evolution

Fix clients_daily to preserve legacy decimal scale

---

src/main/scala/com/mozilla/telemetry/views/ClientsDailyView.scala
src/main/scala/com/mozilla/telemetry/views/dau/GenericDauTrait.scala

I talked with mreid and we should revert this change, because it's having downstream effects that are better off isolated to the parquet-to-bigquery infrastructure

Revert recent changes to clients_daily_v6

---

src/main/scala/com/mozilla/telemetry/views/CrashSummaryView.scala

* Integrate accumulation of processed/discarded counts into map
* Use cached accumulator values to calculate total (as opposed to
getting the size all over again)

Optimize crash summary view

---

src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
src/test/scala/com/mozilla/telemetry/views/MainSummaryViewTest.scala

[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1567339)
This adds `experiment` and `variation` stub attribution fields to main_summary. Unfortunately, attribution was originally added as a nested field, so it can't be updated to accommodate these new fields. They've been added as `attribution_experiment` and `attribution_variation` at the top level instead.
The BigQuery tables are a better choice in this case (see this [schema diff](https://github.com/mozilla-services/mozilla-pipeline-schemas/commit/03466d5532a89c107889ebf3badf333d7da89534)).

Bug 1567339 - Add parameters to attribution in environment data

---

src/main/scala/com/mozilla/telemetry/utils/SyncPingConversion.scala
src/test/scala/com/mozilla/telemetry/views/SyncViewTest.scala
src/test/scala/com/mozilla/telemetry/views/SyncViewTestPayloads.scala

The `steps` field is a new field added to the Sync ping in https://bugzilla.mozilla.org/show_bug.cgi?id=1552621. Each step has a name, millisecond time, and optional named counts, using the same format as validation problems. We use these in new bookmark sync, to report timings and counts for each stage.
This extracts the steps into the summary view (but not the flat engines view), so that we can query them.

Add extractors for Sync engine steps

---

src/main/scala/com/mozilla/telemetry/utils/MainPing.scala
src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala
src/test/scala/com/mozilla/telemetry/views/MainSummaryViewTest.scala

There's a new property in the experiments block, `enrollmentId`, which is a uuid per experiment enrollment, which should help us distinguish duplicate client IDs. Unfortunately, the way I originally set up the experiments block in main summary, it was a simple map of `experiment_id` -> `branch` and structural changes at this sublevel are disallowed per parquet schema evolution. This PR adds a new field, `experiments_details` structured `experiment_id -> Map(String, String)` which adds the `enrollmentId` as well as `type` properties.

Bug 1565600: Add new field with whole experiments object
